-- Flota CADINC — gastos por vehículo.
-- Modelo simple sin workflow de aprobación ni reintegros (esto es flota
-- interna, no transporte de terceros). Solo registro de gastos con
-- comprobante opcional.

create table if not exists public.flota_gastos_categorias (
  id      serial primary key,
  codigo  text not null unique,
  nombre  text not null,
  icono   text,
  orden   integer not null default 99,
  activo  boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.flota_gastos_categorias (codigo, nombre, icono, orden) values
  ('combustible',  'Combustible',         '⛽', 1),
  ('peaje',        'Peajes',              '🛣',  2),
  ('lavado',       'Lavado / detallado',  '🧼', 3),
  ('mantenimiento','Mantenimiento extra', '🔧', 4),
  ('estacionamiento', 'Estacionamiento',  '🅿️', 5),
  ('multa',        'Multa',               '🚓', 6),
  ('otro',         'Otro',                '📋', 99)
on conflict (codigo) do nothing;

alter table public.flota_gastos_categorias enable row level security;
drop policy if exists flota_gastos_categorias_all on public.flota_gastos_categorias;
create policy flota_gastos_categorias_all
  on public.flota_gastos_categorias for all
  using (true) with check (true);

create table if not exists public.flota_gastos (
  id                integer generated by default as identity primary key,
  vehiculo_id       integer not null references public.flota_vehiculos(id) on delete cascade,
  categoria_id      integer references public.flota_gastos_categorias(id) on delete set null,
  fecha             date not null default current_date,
  monto             numeric not null check (monto >= 0),
  proveedor         text,
  descripcion       text,
  comprobante_path  text,
  comprobante_hash  text unique,
  created_by        uuid,
  created_at        timestamptz not null default now(),
  updated_by        uuid,
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz
);

create index if not exists flota_gastos_vehiculo_idx
  on public.flota_gastos (vehiculo_id, fecha desc)
  where deleted_at is null;

create index if not exists flota_gastos_categoria_idx
  on public.flota_gastos (categoria_id)
  where deleted_at is null;

alter table public.flota_gastos enable row level security;
drop policy if exists flota_gastos_all on public.flota_gastos;
create policy flota_gastos_all
  on public.flota_gastos for all
  using (true) with check (true);

drop trigger if exists flota_gastos_touch on public.flota_gastos;
create trigger flota_gastos_touch
  before update on public.flota_gastos
  for each row execute function public._flota_touch_updated_at();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'flota-gastos',
  'flota-gastos',
  false,
  5242880,
  array['image/jpeg','image/png','image/webp','image/heic','image/heif','application/pdf']
)
on conflict (id) do nothing;
