-- ═══════════════════════════════════════════════════════════════════
--  Cuenta del cliente — cobros (pagos del cliente)
-- ───────────────────────────────────────────────────────────────────
--  Registra lo que el cliente le paga a CADINC por los materiales que se
--  le adelantaron (materiales_a_cuenta_cliente). Pago a cuenta de la OBRA,
--  sin imputar a ítems puntuales. El saldo por obra =
--    adeudado (Σ MCC con pagado_por='cadinc') − Σ cobros.
--  Espejo de alquiler_cobros / aridos_cobros (sin imputación).
--  Medio: efectivo / transferencia / cheque / otro.
-- ═══════════════════════════════════════════════════════════════════

create table if not exists public.cuenta_cliente_cobros (
  id          integer generated by default as identity primary key,
  obra_cod    text       not null references public.obras(cod),
  fecha       date       not null,
  monto       numeric    not null check (monto > 0),
  medio       text       not null default 'efectivo'
              check (medio in ('efectivo','transferencia','cheque','otro')),
  obs         text,
  created_by  uuid,
  created_at  timestamptz not null default now(),
  updated_by  uuid,
  updated_at  timestamptz not null default now()
);

create index if not exists cuenta_cliente_cobros_obra_fecha_idx
  on public.cuenta_cliente_cobros (obra_cod, fecha);

-- RLS permisiva por diseño (la seguridad real está en el backend Hono; ver
-- CLAUDE.md §5.4). Mismo patrón que el resto del esquema.
alter table public.cuenta_cliente_cobros enable row level security;
drop policy if exists cuenta_cliente_cobros_all on public.cuenta_cliente_cobros;
create policy cuenta_cliente_cobros_all on public.cuenta_cliente_cobros
  for all using (true) with check (true);
