-- 20260905n — Sinónimos para los 79 materiales que se usaron en pedidos y no tenían ninguno
--
-- El buscador del pedido y el auto-vínculo del barrido matchean nombre + alias
-- normalizados: sin alias, un material se encuentra solo si lo escriben igual
-- que el catálogo. Estos 79 ya salieron en pedidos (los escriben) y no tenían
-- ni uno. Alias como los piden en obra (sin tildes, en minúscula, con las
-- variantes de medida). Solo se agregan: no se toca nombre ni precio.

update public.stock_materiales m set alias = array(select distinct unnest(m.alias || v.a))
from (values
  (450,  array['antioxido','antioxido 1 litro','antioxido x 1','antioxido 3 en 1 1 litro','convertidor de oxido 1 lt']),
  (345,  array['fijador 1 litro','fijador x 1','fijador sellador 1 lt','fijador chico','fijador al agua 1 lt']),
  (3,    array['caño pvc 63','caño de 63','caño 63 x 4','caño 63 pvc','caño desague 63','caño duratop 63']),
  (15,   array['caño termofusion 20','caño fusion 20','caño de 20 fusion','caño 20 ff','caño ppr 20','caño 1/2 fusion']),
  (146,  array['candado','candados','candado 40','candado para porton','candado para cajon']),
  (653,  array['barbijo','barbijos','barbijos descartables','tapaboca','tapabocas','barbijo comun']),
  (203,  array['cupla termofusion 25','cupla fusion 25','cupla de 25','cupla 25 ff','cupla ppr 25']),
  (122,  array['esmalte sintetico 4 litros','esmalte x 4','esmalte sintetico x 4','esmalte 4 lts','sintetico 4 litros']),
  (242,  array['termica 2x16','termica 16 amperes','llave termica 2x16','termica bipolar 16','termica 16a']),
  (224,  array['rejilla 10x10','rejilla de piso 10','rejilla inox 10x10','rejilla 10 x 10']),
  (63,   array['portalampara','portalamparas','zocalo e27','portalampara e27','rosca e27']),
  (696,  array['sika 221','sikaflex 221','sellador sika 221','mapleflex pu','sellador poliuretanico sika']),
  (700,  array['esmalte blanco 4 litros','esmalte sintetico blanco 4','sintetico blanco x 4','esmalte blanco brillante 4 lts']),
  (946,  array['latex 7689','pintura 7689','latex cod 7689','pintura latex 7689']),
  (214,  array['griferia baño','griferia monocomando','griferia lavatorio','griferia lavamanos','monocomando lavatorio','canilla monocomando baño']),
  (401,  array['silicona acetica','silicona acetica transparente','silicona transparente acetica','silicona 280 acetica']),
  (652,  array['guantes de latex','guante latex','guantes de goma','guantes de plastico','guantes multiuso','guantes para pintar']),
  (553,  array['crucetas 2mm','crucetas','separadores 2mm','crucetas separadoras','separadores de ceramico 2mm']),
  (269,  array['lampara 15w','lampara led 15','foco 15w','foco led 15w','lamparita 15w','bulbo led 15w']),
  (256,  array['caño rigido 3/4','caño rigido de 3/4','caño rigido 20mm','caño rigido 20','metro de caño rigido 3/4']),
  (205,  array['rosca macho 1/2','tubo macho 1/2','rosca macho termofusion 1/2','tubo macho de 20 x 1/2','conexion macho 1/2 fusion']),
  (1,    array['caño pvc 40','caño de 40','caño 40 x 4','caño 40 pvc','caño desague 40','caño 40 awaduct']),
  (662,  array['delantal','delantales','delantal de cuero','delantal soldador','delantal de descarne']),
  (38,   array['cable 4mm','cable 4 mm','cable unipolar 4','cable de 4','cable 4mm2','cable 4 mm2 rojo','cable 4 mm2 celeste']),
  (90,   array['arena','arena fina por tonelada','tonelada de arena fina','arena fina tn']),
  (353,  array['pintura epoxi','pintura epoxi pisos','epoxi 4 litros','pintura epoxi gris','pintura epoxi blanca','epoxi para piso']),
  (11,   array['cupla pvc 40','cupla de 40','cupla 40','cupla 0.40 duratop','cupla 40 desague']),
  (261,  array['conector rigido 1','conector caño rigido 1 pulgada','conector 1 rigido','conector 25mm rigido']),
  (531,  array['ceramico 30x30','ceramico piso 30','ceramica 30x30']),
  (638,  array['tablon','tablon de pino','tablon encofrado','tablon 1 pulgada 4 metros','tablon de madera 4m']),
  (166,  array['electrodo 3.25','electrodos 3.25','electrodo 3,25','electrodos punta azul','electrodos 3.25 x kg']),
  (533,  array['ceramico 45x45','ceramico piso 45','ceramica 45x45']),
  (89,   array['arena gruesa por tonelada','tonelada de arena gruesa','arena de rio gruesa','arena gruesa tn']),
  (760,  array['caja estanca','caja estanca 110','caja estanca pvc','caja de paso estanca','caja estanca 10x10']),
  (191,  array['pileta de patio','pileta de patio 15','pileta patio 15x15','pileta de piso 15x15']),
  (285,  array['superboard 8','placa superboard 8','superboard 8mm','placa cementicia 8mm']),
  (39,   array['cable 6mm','cable 6 mm','cable unipolar 6','cable de 6','cable 6mm2','cable 6 verde amarillo']),
  (951,  array['fuelle inodoro','fuelle de goma','fuelle para inodoro','conexion fuelle inodoro']),
  (955,  array['chapon','chapon 16','chapon calibre 16','chapa calibre 16','chapon de hierro 16']),
  (51,   array['disyuntor 2x40','disyuntor 40','diferencial 2x40','disyuntor 40 amperes','disyuntor bipolar 40']),
  (66,   array['jabalina','jabalina de puesta a tierra','jabalina y tomacable','jabalina 1.5','puesta a tierra jabalina']),
  (1059, array['guante vaqueta','guantes vaqueta','guantes de vaqueta','guante de cuero amarillo','guantes amarillos']),
  (150,  array['silicona blanca','silicona blanca 280','silicona color blanco']),
  (445,  array['mecha 10','mecha acero rapido 10','mecha 10mm','mecha de 10 para metal','mecha hss 10']),
  (698,  array['mecha 5.5','mecha acero rapido 5.5','mecha 5,5','mecha hss 5.5']),
  (446,  array['mecha 12','mecha acero rapido 12','mecha 12mm','mecha de 12 para metal','mecha hss 12']),
  (693,  array['pila recargable','pilas recargables','bateria recargable aa','pilas aa recargables']),
  (694,  array['carbones demoledor','carbones makita','carbones n218','escobillas demoledor','carbones para demoledor']),
  (655,  array['mascara de soldar','mascara fotosensible','mascara soldar automatica','careta fotosensible','mascara de soldador']),
  (133,  array['tornillo madera 4x40','tornillo 4x40','tornillo para madera 40','tornillo 4 x 40']),
  (30,   array['bidet','bide','bidet 3 agujeros','bidet blanco']),
  (6,    array['codo pvc 50','codo de 50','codo 50','codos 0.50 hh 90','codo 50 desague']),
  (12,   array['cupla pvc 50','cupla de 50','cupla 50','cupla 0.50 duratop','cupla 50 desague']),
  (50,   array['disyuntor 2x25','disyuntor 25','diferencial 2x25','disyuntor 25 amperes','disyuntor bipolar 25']),
  (23,   array['flotante','flotante de tanque','flotante para tanque','valvula flotante','flotante automatico']),
  (28,   array['inodoro','inodoro blanco','inodoro comun','inodoro con tapa','inodoro largo']),
  (65,   array['tubo led','tubo led 18','tubo led 18w','tubo led 120','tubo 1.20 led']),
  (2,    array['caño pvc 50','caño de 50','caño 50 x 4','caño 50 pvc','caño desague 50','caño 0.50 duratop']),
  (157,  array['angulo 1 1/2','angulo 1 1/2 x 1/8','angulo de 1 1/2','angulo 1.5 pulgadas','hierro angulo 1 1/2']),
  (93,   array['ladrillo hueco 8','ladrillo 8','hueco 8','ladrillo hueco de 8','ladrillos del 8']),
  (112,  array['latex interior 20','latex interior 20 litros','latex 20 lts interior','pintura latex interior 20','latex blanco interior 20']),
  (153,  array['perfil c 80','perfil c 80x40','perfil c 80x40x15','pc 80','perfil c de 80']),
  (156,  array['angulo 1','angulo 1 x 1/8','angulo de 1 pulgada','angulo 1x1/8','hierro angulo 1']),
  (163,  array['planchuela 1','planchuela 1 x 1/8','planchuela de 1','planchuela 1x1/8']),
  (121,  array['fijador 4 litros','fijador x 4','fijador sellador 4 lts','fijador al agua 4 lts','fijador 4 lts']),
  (207,  array['rosca hembra 1/2','tubo hembra 1/2','rosca hembra termofusion 1/2','tubo hembra de 20 x 1/2','conexion hembra 1/2 fusion']),
  (232,  array['espejo','espejo 60x80','espejo baño','espejo 60 x 80','espejo para baño']),
  (244,  array['termica 2x40','termica 40 amperes','llave termica 2x40','termica bipolar 40','termica 40a']),
  (328,  array['acelerante','acelerante de fraguado','acelerante 5 litros','acelerante sika 3','sika 3']),
  (324,  array['pegamento flex','pegamento piso sobre piso','pegamento flexible','klaukol flex','pegamento porcelanato flex']),
  (270,  array['lampara 20w','lampara led 20','foco 20w','foco led 20w','focos de 20w fria','bulbo led 20w']),
  (354,  array['pintura asfaltica 18','pintura asfaltica 18 litros','tacho de pintura asfaltica','asfaltica 18 lts','pintura asfaltica lata grande']),
  (362,  array['pincel 4','pincel de 4','pincel 4 pulgadas','pincel 10 cm','pincel ancho']),
  (379,  array['tornillo madera 6x80','tornillo 6x80','tornillo para madera 80','tornillo madera largo 80']),
  (406,  array['precinto 30','precintos 30 cm','precinto plastico 30','precintos grandes','precinto 30cm']),
  (411,  array['alambre galvanizado 14','alambre 14','alambre galvanizado n14','alambre galvanizado nro 14','alambre 14 galvanizado']),
  (437,  array['alambre mig','alambre mig 0.8','alambre para soldadora mig','rollo de alambre mig','alambre para la semi','alambre 0.8 mig']),
  (514,  array['ventana corrediza 120x110','ventana aluminio 1.20x1.10','ventana 120x110','ventana corrediza 1.20 x 1.10']),
  (506,  array['puerta de chapa','puerta chapa','puerta exterior chapa','puerta chapa reforzada','puerta de chapa inyectada'])
) as v(id, a)
where m.id = v.id;
