-- ═══════════════════════════════════════════════════════════════════
--  ALQUILER — Fase A de cuenta corriente: clientes (ficha) + $/hora
-- ───────────────────────────────────────────────────────────────────
--  Para llevar la cuenta corriente del mismo cliente entre varias obras,
--  `cliente` pasa de texto libre a una FICHA (entidad). Cada obra apunta a
--  un cliente. Y cada máquina asignada a una obra tiene su precio por hora.
--
--  (Fase B = devengado por parte = horas × precio_hora; Fase C = cobros +
--  extracto/cuenta corriente. No en esta migración.)
-- ═══════════════════════════════════════════════════════════════════

-- 1. Ficha de cliente.
create table if not exists public.alquiler_clientes (
  id          integer generated by default as identity primary key,
  nombre      text       not null,
  cuit        text,
  contacto    text,                              -- persona de contacto
  tel         text,
  email       text,
  obs         text,
  created_by  uuid,
  created_at  timestamptz not null default now(),
  updated_by  uuid,
  updated_at  timestamptz not null default now()
);

create trigger trg_alquiler_clientes_touch
  before update on public.alquiler_clientes
  for each row execute function public._alquiler_touch_updated_at();

alter table public.alquiler_clientes enable row level security;
drop policy if exists alquiler_clientes_all on public.alquiler_clientes;
create policy alquiler_clientes_all on public.alquiler_clientes
  for all using (true) with check (true);

-- 2. La obra apunta a un cliente (se conserva el texto `cliente` por back-compat).
alter table public.alquiler_obras
  add column if not exists cliente_id integer references public.alquiler_clientes(id) on delete set null;
create index if not exists alquiler_obras_cliente_idx
  on public.alquiler_obras (cliente_id) where cliente_id is not null;

-- 3. Precio por hora de la máquina EN la obra (en la asignación).
alter table public.alquiler_obra_maquinas
  add column if not exists precio_hora numeric;

-- 4. Migrar el texto `cliente` existente a fichas y linkear las obras.
insert into public.alquiler_clientes (nombre)
select distinct trim(cliente)
from public.alquiler_obras
where cliente is not null and trim(cliente) <> ''
  and not exists (
    select 1 from public.alquiler_clientes c where c.nombre = trim(public.alquiler_obras.cliente)
  );

update public.alquiler_obras o
set cliente_id = c.id
from public.alquiler_clientes c
where o.cliente_id is null
  and o.cliente is not null and trim(o.cliente) <> ''
  and c.nombre = trim(o.cliente);
