-- ═══════════════════════════════════════════════════════════════════
--  MÓDULO ALQUILER DE MAQUINARIA — Fase 2: remito diario
-- ───────────────────────────────────────────────────────────────────
--  Un remito por (máquina, día) — es decir, 1:1 con `alquiler_partes`.
--  El remito es el documento que se imprime y se le manda al cliente
--  (A4 + WhatsApp/PDF). Se numera correlativo RA-NNNN.
--
--  DISEÑO (decidido con el user):
--    - Numeración: RA-0001, RA-0002… correlativa global (MAX+1, igual que
--      RR-NNNN de remitos_retiro_proveedor). Gaps tolerados.
--    - El remito SNAPSHOTEA los datos mostrados (obra, cliente, ubicación,
--      máquina, horarios, horas, detalle) al momento de emitir. Así el
--      documento es self-contained y no cambia si después se toca el ABM
--      de la máquina/obra. La emisión es IDEMPOTENTE: re-emitir el mismo
--      parte REFRESCA el snapshot desde el parte actual pero CONSERVA el
--      número (no consume uno nuevo).
--    - 1 remito por parte → UNIQUE(parte_id). Emitir = `emitir_remito_alquiler`.
--
--  SEGURIDAD (CLAUDE.md §9): el RPC es SECURITY DEFINER y se llama SOLO con
--  el cliente admin (service_role) desde el backend. EXECUTE revocado para
--  public/authenticated. Las validaciones de permiso corren en el backend
--  ANTES del RPC; el RPC recibe p_user_id explícito (no usa auth.uid()).
-- ═══════════════════════════════════════════════════════════════════

-- ── 1. Tabla alquiler_remitos ──────────────────────────────────────
create table if not exists public.alquiler_remitos (
  id                     integer generated by default as identity primary key,
  numero                 text       not null unique,                 -- 'RA-0001'
  -- 1:1 con el parte. CASCADE: si se borra el parte, se borra el remito.
  parte_id               integer    not null unique
                         references public.alquiler_partes(id) on delete cascade,
  -- referencias "vivas" (para joins/filtros); SET NULL para no perder el
  -- remito si se borra la obra/máquina. El snapshot de abajo preserva los datos.
  obra_id                integer    references public.alquiler_obras(id)    on delete set null,
  maquina_id             integer    references public.alquiler_maquinas(id) on delete set null,
  fecha_trabajo          date       not null,                        -- snapshot de parte.fecha
  -- ── snapshot obra ──
  obra_nombre            text,
  cliente                text,
  ubicacion              text,
  -- ── snapshot máquina ──
  maquina_nombre         text,
  maquina_tipo           text,
  maquina_identificacion text,
  -- ── snapshot horarios + horas + detalle ──
  manana_entrada         time,
  manana_salida          time,
  tarde_entrada          time,
  tarde_salida           time,
  horas                  numeric    not null default 0,
  detalle                text,
  fecha_emision          date       not null default current_date,
  created_by             uuid,
  created_at             timestamptz not null default now(),
  updated_by             uuid,
  updated_at             timestamptz not null default now()
);

create index if not exists alquiler_remitos_obra_fecha_idx
  on public.alquiler_remitos (obra_id, fecha_trabajo);
create index if not exists alquiler_remitos_maquina_fecha_idx
  on public.alquiler_remitos (maquina_id, fecha_trabajo);

create trigger trg_alquiler_remitos_touch
  before update on public.alquiler_remitos
  for each row execute function public._alquiler_touch_updated_at();

alter table public.alquiler_remitos enable row level security;
drop policy if exists alquiler_remitos_all on public.alquiler_remitos;
create policy alquiler_remitos_all on public.alquiler_remitos
  for all using (true) with check (true);

-- ── 2. RPC emitir_remito_alquiler(parte_id, user_id) ───────────────
--  Crea (o refresca) el remito del parte y devuelve la fila completa.
--  - Si el parte ya tiene remito → UPDATE del snapshot, MISMO número.
--  - Si no → numera RA-NNNN (MAX+1) e inserta.
--  Un advisory lock global serializa las emisiones (volumen bajo): evita
--  tanto números duplicados como doble-INSERT por doble-click del mismo parte.
create or replace function public.emitir_remito_alquiler(
  p_parte_id integer,
  p_user_id  uuid
) returns public.alquiler_remitos
language plpgsql
security definer
set search_path = public
as $$
declare
  v_parte   public.alquiler_partes%rowtype;
  v_obra    public.alquiler_obras%rowtype;
  v_maquina public.alquiler_maquinas%rowtype;
  v_remito  public.alquiler_remitos%rowtype;
  v_seq     integer;
  v_numero  text;
begin
  -- Serializa todas las emisiones (numeración + idempotencia por parte).
  perform pg_advisory_xact_lock(hashtext('alquiler_remito_emit'));

  select * into v_parte from public.alquiler_partes where id = p_parte_id;
  if v_parte.id is null then
    raise exception 'PARTE_NO_EXISTE' using errcode = 'P0001';
  end if;

  select * into v_obra    from public.alquiler_obras    where id = v_parte.obra_id;
  select * into v_maquina from public.alquiler_maquinas where id = v_parte.maquina_id;

  -- ¿ya hay remito para este parte? → refrescar snapshot, conservar número.
  select * into v_remito from public.alquiler_remitos where parte_id = p_parte_id;

  if v_remito.id is not null then
    update public.alquiler_remitos set
      obra_id                = v_parte.obra_id,
      maquina_id             = v_parte.maquina_id,
      fecha_trabajo          = v_parte.fecha,
      obra_nombre            = v_obra.nombre,
      cliente                = v_obra.cliente,
      ubicacion              = v_obra.ubicacion,
      maquina_nombre         = v_maquina.nombre,
      maquina_tipo           = v_maquina.tipo,
      maquina_identificacion = v_maquina.identificacion,
      manana_entrada         = v_parte.manana_entrada,
      manana_salida          = v_parte.manana_salida,
      tarde_entrada          = v_parte.tarde_entrada,
      tarde_salida           = v_parte.tarde_salida,
      horas                  = coalesce(v_parte.horas, 0),
      detalle                = v_parte.detalle,
      updated_by             = p_user_id,
      updated_at             = now()
    where id = v_remito.id
    returning * into v_remito;
    return v_remito;
  end if;

  -- Nuevo remito → número correlativo RA-NNNN.
  select coalesce(max(nullif(regexp_replace(numero, '[^0-9]', '', 'g'), '')::integer), 0) + 1
  into v_seq
  from public.alquiler_remitos
  where numero like 'RA-%';
  v_numero := 'RA-' || lpad(v_seq::text, 4, '0');

  insert into public.alquiler_remitos (
    numero, parte_id, obra_id, maquina_id, fecha_trabajo,
    obra_nombre, cliente, ubicacion,
    maquina_nombre, maquina_tipo, maquina_identificacion,
    manana_entrada, manana_salida, tarde_entrada, tarde_salida,
    horas, detalle, created_by, updated_by
  ) values (
    v_numero, p_parte_id, v_parte.obra_id, v_parte.maquina_id, v_parte.fecha,
    v_obra.nombre, v_obra.cliente, v_obra.ubicacion,
    v_maquina.nombre, v_maquina.tipo, v_maquina.identificacion,
    v_parte.manana_entrada, v_parte.manana_salida, v_parte.tarde_entrada, v_parte.tarde_salida,
    coalesce(v_parte.horas, 0), v_parte.detalle, p_user_id, p_user_id
  )
  returning * into v_remito;

  return v_remito;
end;
$$;

-- §9: solo service_role ejecuta funciones SECURITY DEFINER. Supabase tiene
-- default privileges que otorgan EXECUTE explícito a anon/authenticated en el
-- schema public, así que `revoke from public` no alcanza: hay que revocar de
-- esos roles por nombre.
revoke execute on function public.emitir_remito_alquiler(integer, uuid)
  from public, anon, authenticated;
grant execute on function public.emitir_remito_alquiler(integer, uuid) to service_role;
