-- Flota CADINC — Fase 2: registro de services de mantenimiento por vehículo.
-- Cada service guarda lo realizado (tipo del catálogo o texto libre), km al
-- momento, y opcionalmente próximo objetivo (km o fecha) que dispara la vista
-- v_flota_servicios_estado. Soporta comprobante PDF/imagen con dedup por sha256.

create table if not exists public.flota_servicios (
  id                integer generated by default as identity primary key,
  vehiculo_id       integer not null references public.flota_vehiculos(id) on delete cascade,
  tipo_id           integer references public.flota_tipos_servicio(id) on delete set null,
  tipo_libre        text,
  fecha             date not null default current_date,
  km_service        numeric not null,
  km_proximo        numeric,
  fecha_proximo     date,
  descripcion       text,
  costo             numeric,
  proveedor         text,
  comprobante_path  text,
  comprobante_hash  text,
  obs               text,
  created_by        uuid,
  created_at        timestamptz not null default now(),
  updated_by        uuid,
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz,
  constraint flota_servicios_tipo_chk check (
    tipo_id is not null or (tipo_libre is not null and length(trim(tipo_libre)) > 0)
  ),
  constraint flota_servicios_comprobante_uq unique (comprobante_hash)
);

create index if not exists flota_servicios_vehiculo_idx
  on public.flota_servicios (vehiculo_id, fecha desc)
  where deleted_at is null;

alter table public.flota_servicios enable row level security;
drop policy if exists flota_servicios_all on public.flota_servicios;
create policy flota_servicios_all
  on public.flota_servicios for all
  using (true) with check (true);

drop trigger if exists flota_servicios_touch on public.flota_servicios;
create trigger flota_servicios_touch
  before update on public.flota_servicios
  for each row execute function public._flota_touch_updated_at();

-- Bucket de comprobantes (5MB, imágenes y PDF). Privado: se accede vía signed URL.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'flota-servicios',
  'flota-servicios',
  false,
  5242880,
  array['image/jpeg','image/png','image/webp','image/heic','image/heif','application/pdf']
)
on conflict (id) do nothing;
