-- Áridos — lista de precios GLOBAL por material (con historial de
-- vigencia). Resolución del precio de venta:
--   1. precio del CLIENTE para el material (override, vigente a la fecha)
--   2. si no hay, precio GLOBAL (vigente a la fecha)
--   3. si no hay ninguno, precio especial a mano.
CREATE TABLE IF NOT EXISTS aridos_precios_global (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material_id   INT NOT NULL REFERENCES aridos_materiales(id) ON DELETE CASCADE,
  precio        NUMERIC NOT NULL CHECK (precio >= 0),
  vigente_desde DATE NOT NULL DEFAULT CURRENT_DATE,
  obs           TEXT,
  created_by    UUID,
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_by    UUID,
  updated_at    TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_aridos_precios_global
  ON aridos_precios_global (material_id, vigente_desde DESC);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = '_alquiler_touch_updated_at') THEN
    CREATE TRIGGER trg_touch_aridos_precios_global BEFORE UPDATE ON aridos_precios_global FOR EACH ROW EXECUTE FUNCTION _alquiler_touch_updated_at();
  END IF;
END $$;

ALTER TABLE aridos_precios_global ENABLE ROW LEVEL SECURITY;
CREATE POLICY aridos_precios_global_all ON aridos_precios_global FOR ALL USING (true) WITH CHECK (true);
