-- ════════════════════════════════════════════════════════════════════
-- Módulo ÁRIDOS — venta de áridos por m³ / retiro de escombros por viaje
-- Cuentas corrientes por cliente + stock en depósito propio (único).
-- Convenciones calcadas del módulo alquiler (20260602_alquiler_maquinaria).
-- ════════════════════════════════════════════════════════════════════

-- Catálogo de materiales (arena, piedra, ...) con su unidad de venta.
CREATE TABLE IF NOT EXISTS aridos_materiales (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre     TEXT NOT NULL UNIQUE,
  unidad     TEXT NOT NULL DEFAULT 'm3' CHECK (unidad IN ('m3', 'viaje')),
  activo     BOOLEAN NOT NULL DEFAULT true,
  created_by UUID,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_by UUID,
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Clientes de áridos (mayoría externos; las obras propias se cargan
-- como un cliente más para que la cuenta corriente funcione igual).
CREATE TABLE IF NOT EXISTS aridos_clientes (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre     TEXT NOT NULL,
  cuit       TEXT,
  tel        TEXT,
  email      TEXT,
  direccion  TEXT,
  obs        TEXT,
  created_by UUID,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_by UUID,
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Precios preestablecidos por cliente × material, con historial de
-- vigencia (mismo patrón que tarifas_empresa_cantera): al vender se
-- toma el precio con vigente_desde más reciente <= fecha de la venta.
CREATE TABLE IF NOT EXISTS aridos_precios_cliente (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id    INT NOT NULL REFERENCES aridos_clientes(id) ON DELETE CASCADE,
  material_id   INT NOT NULL REFERENCES aridos_materiales(id) ON DELETE CASCADE,
  precio        NUMERIC NOT NULL CHECK (precio >= 0),
  vigente_desde DATE NOT NULL DEFAULT CURRENT_DATE,
  obs           TEXT,
  created_by    UUID,
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_by    UUID,
  updated_at    TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_aridos_precios_cliente
  ON aridos_precios_cliente (cliente_id, material_id, vigente_desde DESC);

-- Movimientos: ventas (cargo en cta cte), acopios cantera→depósito y
-- ajustes de inventario. Stock del depósito por material =
--   acopios + ajustes − ventas con origen='deposito'.
-- Ventas con origen='cantera' van directo al cliente sin tocar stock.
CREATE TABLE IF NOT EXISTS aridos_movimientos (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo        TEXT NOT NULL CHECK (tipo IN ('venta', 'acopio', 'ajuste')),
  fecha       DATE NOT NULL DEFAULT CURRENT_DATE,
  material_id INT NOT NULL REFERENCES aridos_materiales(id),
  -- m3 o viajes según unidad del material; en ajustes puede ser negativa
  cantidad    NUMERIC NOT NULL,
  -- venta: de dónde sale el material; acopio/ajuste: NULL (siempre depósito)
  origen      TEXT CHECK (origen IN ('cantera', 'deposito')),
  cantera_id  INT REFERENCES canteras(id),
  cliente_id  INT REFERENCES aridos_clientes(id),
  precio_unit NUMERIC,
  importe     NUMERIC,
  chofer_id   INT REFERENCES choferes(id),
  camion_id   INT REFERENCES camiones(id),
  flete_obs   TEXT,
  remito      TEXT,
  obs         TEXT,
  created_by  UUID,
  created_at  TIMESTAMPTZ DEFAULT now(),
  updated_by  UUID,
  updated_at  TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT venta_requiere_cliente CHECK (tipo <> 'venta' OR cliente_id IS NOT NULL),
  CONSTRAINT venta_requiere_origen  CHECK (tipo <> 'venta' OR origen IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS idx_aridos_mov_cliente  ON aridos_movimientos (cliente_id, fecha);
CREATE INDEX IF NOT EXISTS idx_aridos_mov_material ON aridos_movimientos (material_id, tipo);

-- Cobros del cliente (cta cte: saldo = Σ importes de ventas − Σ cobros)
CREATE TABLE IF NOT EXISTS aridos_cobros (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id INT NOT NULL REFERENCES aridos_clientes(id) ON DELETE RESTRICT,
  fecha      DATE NOT NULL DEFAULT CURRENT_DATE,
  monto      NUMERIC NOT NULL CHECK (monto > 0),
  medio      TEXT NOT NULL DEFAULT 'transferencia' CHECK (medio IN ('efectivo', 'transferencia', 'cheque', 'otro')),
  obs        TEXT,
  created_by UUID,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_by UUID,
  updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_aridos_cobros_cliente ON aridos_cobros (cliente_id, fecha);

-- Trigger touch updated_at (reusa la función del módulo alquiler)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = '_alquiler_touch_updated_at') THEN
    CREATE TRIGGER trg_touch_aridos_materiales      BEFORE UPDATE ON aridos_materiales      FOR EACH ROW EXECUTE FUNCTION _alquiler_touch_updated_at();
    CREATE TRIGGER trg_touch_aridos_clientes        BEFORE UPDATE ON aridos_clientes        FOR EACH ROW EXECUTE FUNCTION _alquiler_touch_updated_at();
    CREATE TRIGGER trg_touch_aridos_precios_cliente BEFORE UPDATE ON aridos_precios_cliente FOR EACH ROW EXECUTE FUNCTION _alquiler_touch_updated_at();
    CREATE TRIGGER trg_touch_aridos_movimientos     BEFORE UPDATE ON aridos_movimientos     FOR EACH ROW EXECUTE FUNCTION _alquiler_touch_updated_at();
    CREATE TRIGGER trg_touch_aridos_cobros          BEFORE UPDATE ON aridos_cobros          FOR EACH ROW EXECUTE FUNCTION _alquiler_touch_updated_at();
  END IF;
END $$;

-- RLS permisiva (seguridad real en backend Hono, como todo el sistema)
ALTER TABLE aridos_materiales      ENABLE ROW LEVEL SECURITY;
ALTER TABLE aridos_clientes        ENABLE ROW LEVEL SECURITY;
ALTER TABLE aridos_precios_cliente ENABLE ROW LEVEL SECURITY;
ALTER TABLE aridos_movimientos     ENABLE ROW LEVEL SECURITY;
ALTER TABLE aridos_cobros          ENABLE ROW LEVEL SECURITY;
CREATE POLICY aridos_materiales_all      ON aridos_materiales      FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY aridos_clientes_all        ON aridos_clientes        FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY aridos_precios_cliente_all ON aridos_precios_cliente FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY aridos_movimientos_all     ON aridos_movimientos     FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY aridos_cobros_all          ON aridos_cobros          FOR ALL USING (true) WITH CHECK (true);

-- Seed del catálogo
INSERT INTO aridos_materiales (nombre, unidad) VALUES
  ('Arena', 'm3'),
  ('Piedra', 'm3'),
  ('Tierra', 'm3'),
  ('Relleno', 'm3'),
  ('Ripio bruto', 'm3'),
  ('Ripio fino', 'm3'),
  ('Retiro de escombro', 'viaje')
ON CONFLICT (nombre) DO NOTHING;
