-- ═══════════════════════════════════════════════════════════════════
--  MÓDULO ALQUILER DE MAQUINARIA — Fase 1
-- ───────────────────────────────────────────────────────────────────
--  CADINC alquila maquinaria (hidrogrúa, retropala, minicargadora,
--  trailer con canasta, etc.) a clientes. El flujo:
--    1. Se crea una "obra de alquiler" (ej. "San Pablo"). Es un concepto
--       SEPARADO de las obras de construcción (tabla `obras`); por eso
--       vive en su propia tabla `alquiler_obras` — NO se mezcla con
--       `obras` ni con `obra_cod`.
--    2. A esa obra se le ASIGNAN máquinas de la flota (`alquiler_maquinas`)
--       vía `alquiler_obra_maquinas`.
--    3. A cada máquina asignada se le asigna un MAQUINISTA (el user que
--       carga las horas de esa máquina) y a la obra un JEFE DE OBRA
--       (consulta read-only). Ambos son FK a `profiles(id)`.
--    4. El maquinista carga, por día y por máquina, las horas de
--       entrada/salida de turno mañana y tarde + detalle de trabajos
--       en `alquiler_partes`.
--
--  Cliente es TEXTO LIBRE (decisión del user: no hay ABM de clientes).
--
--  FASE 2 (NO en esta migración): remitos diarios por máquina/día.
--
--  Convenciones (calcadas del módulo flota, mig 20260513/20260518):
--    - PK `integer generated by default as identity` (estilo moderno del
--      proyecto; equivalente a serial pero sin la secuencia legacy).
--    - Auditoría: created_at/updated_at (timestamptz default now()),
--      created_by/updated_by (uuid). Trigger touch para updated_at.
--    - RLS habilitada con policy PERMISIVA `using(true) with check(true)`
--      (CLAUDE.md §5.4: la seguridad real está en el backend Hono; la
--      anon key NO muta datos).
--    - FK a profiles(id) con ON DELETE SET NULL (no queremos borrar un
--      parte/asignación porque se dio de baja un usuario).
-- ═══════════════════════════════════════════════════════════════════

-- ── Trigger touch compartido del módulo ────────────────────────────
-- `set search_path = public` para silenciar el advisor
-- function_search_path_mutable (ver mig 20260527_function_search_path).
create or replace function public._alquiler_touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ════════════════════════════════════════════════════════════════════
-- 1. alquiler_maquinas — la flota de maquinaria
-- ════════════════════════════════════════════════════════════════════
create table if not exists public.alquiler_maquinas (
  id              integer generated by default as identity primary key,
  nombre          text       not null,
  tipo            text       not null default 'otro'
                  check (tipo in (
                    'hidrogrua',
                    'retropala',
                    'minicargadora',
                    'trailer_canasta',
                    'otro'
                  )),
  identificacion  text,                              -- patente o nº interno (nullable)
  estado          text       not null default 'activa'
                  check (estado in ('activa','mantenimiento','inactiva')),
  obs             text,
  created_by      uuid,
  created_at      timestamptz not null default now(),
  updated_by      uuid,
  updated_at      timestamptz not null default now()
);

create index if not exists alquiler_maquinas_estado_idx
  on public.alquiler_maquinas (estado);

create trigger trg_alquiler_maquinas_touch
  before update on public.alquiler_maquinas
  for each row execute function public._alquiler_touch_updated_at();

alter table public.alquiler_maquinas enable row level security;
drop policy if exists alquiler_maquinas_all on public.alquiler_maquinas;
create policy alquiler_maquinas_all on public.alquiler_maquinas
  for all using (true) with check (true);

-- ════════════════════════════════════════════════════════════════════
-- 2. alquiler_obras — la obra de alquiler (separada de `obras`)
-- ════════════════════════════════════════════════════════════════════
create table if not exists public.alquiler_obras (
  id                 integer generated by default as identity primary key,
  nombre             text       not null,             -- ej. "San Pablo"
  cliente            text,                             -- TEXTO LIBRE (sin ABM de clientes)
  ubicacion          text,
  descripcion        text,
  jefe_obra_user_id  uuid       references public.profiles(id) on delete set null,
  estado             text       not null default 'activa'
                     check (estado in ('activa','cerrada')),
  fecha_inicio       date,
  obs                text,
  created_by         uuid,
  created_at         timestamptz not null default now(),
  updated_by         uuid,
  updated_at         timestamptz not null default now()
);

create index if not exists alquiler_obras_estado_idx
  on public.alquiler_obras (estado);
create index if not exists alquiler_obras_jefe_obra_idx
  on public.alquiler_obras (jefe_obra_user_id)
  where jefe_obra_user_id is not null;

create trigger trg_alquiler_obras_touch
  before update on public.alquiler_obras
  for each row execute function public._alquiler_touch_updated_at();

alter table public.alquiler_obras enable row level security;
drop policy if exists alquiler_obras_all on public.alquiler_obras;
create policy alquiler_obras_all on public.alquiler_obras
  for all using (true) with check (true);

-- ════════════════════════════════════════════════════════════════════
-- 3. alquiler_obra_maquinas — asignación máquina ↔ obra + maquinista
-- ════════════════════════════════════════════════════════════════════
create table if not exists public.alquiler_obra_maquinas (
  id                  integer generated by default as identity primary key,
  obra_id             integer    not null references public.alquiler_obras(id) on delete cascade,
  maquina_id          integer    not null references public.alquiler_maquinas(id),
  maquinista_user_id  uuid       references public.profiles(id) on delete set null,
  created_by          uuid,
  created_at          timestamptz not null default now(),
  updated_by          uuid,
  updated_at          timestamptz not null default now(),
  -- una máquina no se asigna dos veces a la misma obra
  constraint alquiler_obra_maquinas_obra_maquina_uq unique (obra_id, maquina_id)
);

-- FK index para joins y para que CASCADE/lookup por obra sea barato
create index if not exists alquiler_obra_maquinas_obra_idx
  on public.alquiler_obra_maquinas (obra_id);
create index if not exists alquiler_obra_maquinas_maquina_idx
  on public.alquiler_obra_maquinas (maquina_id);
-- "qué máquinas carga este maquinista"
create index if not exists alquiler_obra_maquinas_maquinista_idx
  on public.alquiler_obra_maquinas (maquinista_user_id)
  where maquinista_user_id is not null;

create trigger trg_alquiler_obra_maquinas_touch
  before update on public.alquiler_obra_maquinas
  for each row execute function public._alquiler_touch_updated_at();

alter table public.alquiler_obra_maquinas enable row level security;
drop policy if exists alquiler_obra_maquinas_all on public.alquiler_obra_maquinas;
create policy alquiler_obra_maquinas_all on public.alquiler_obra_maquinas
  for all using (true) with check (true);

-- ════════════════════════════════════════════════════════════════════
-- 4. alquiler_partes — parte diario de horas por (día, obra, máquina)
-- ════════════════════════════════════════════════════════════════════
create table if not exists public.alquiler_partes (
  id              integer generated by default as identity primary key,
  obra_id         integer    not null references public.alquiler_obras(id) on delete cascade,
  maquina_id      integer    not null references public.alquiler_maquinas(id),
  fecha           date       not null,
  manana_entrada  time,
  manana_salida   time,
  tarde_entrada   time,
  tarde_salida    time,
  horas           numeric,                           -- total; lo calcula front/back, columna reservada
  detalle         text,                              -- trabajos realizados
  obs             text,
  created_by      uuid,
  created_at      timestamptz not null default now(),
  updated_by      uuid,
  updated_at      timestamptz not null default now(),
  -- un único parte por máquina/obra/día
  constraint alquiler_partes_obra_maquina_fecha_uq unique (obra_id, maquina_id, fecha)
);

create index if not exists alquiler_partes_obra_fecha_idx
  on public.alquiler_partes (obra_id, fecha);
create index if not exists alquiler_partes_maquina_fecha_idx
  on public.alquiler_partes (maquina_id, fecha);

create trigger trg_alquiler_partes_touch
  before update on public.alquiler_partes
  for each row execute function public._alquiler_touch_updated_at();

alter table public.alquiler_partes enable row level security;
drop policy if exists alquiler_partes_all on public.alquiler_partes;
create policy alquiler_partes_all on public.alquiler_partes
  for all using (true) with check (true);
