-- ════════════════════════════════════════════════════════════════════
-- Áridos v1.1 — entrega, costos de cantera, municipios y precio especial
-- 1) Dirección/municipio de entrega en cada venta (o de retiro, escombro).
-- 2) Origen 'obra' para retiros de escombro (obra del cliente → depósito).
-- 3) Costos de compra por cantera × material (historial por vigencia).
-- 4) Flag precio_especial para trazabilidad (lista vs cotizado a mano).
-- 5) Municipios con recargo % sobre el precio base (zonas alejadas).
-- ════════════════════════════════════════════════════════════════════

-- Municipios / zonas de entrega con recargo porcentual
CREATE TABLE IF NOT EXISTS aridos_municipios (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      TEXT NOT NULL UNIQUE,
  recargo_pct NUMERIC NOT NULL DEFAULT 0 CHECK (recargo_pct >= 0),
  obs         TEXT,
  created_by  UUID,
  created_at  TIMESTAMPTZ DEFAULT now(),
  updated_by  UUID,
  updated_at  TIMESTAMPTZ DEFAULT now()
);

-- Costo de compra por cantera × material, con historial de vigencia
-- (qué nos cuesta el m³ en cada cantera; para margen venta − costo)
CREATE TABLE IF NOT EXISTS aridos_costos_cantera (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cantera_id    INT NOT NULL REFERENCES canteras(id) ON DELETE CASCADE,
  material_id   INT NOT NULL REFERENCES aridos_materiales(id) ON DELETE CASCADE,
  costo         NUMERIC NOT NULL CHECK (costo >= 0),
  vigente_desde DATE NOT NULL DEFAULT CURRENT_DATE,
  obs           TEXT,
  created_by    UUID,
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_by    UUID,
  updated_at    TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_aridos_costos_cantera
  ON aridos_costos_cantera (cantera_id, material_id, vigente_desde DESC);

-- Movimientos: entrega + municipio + precio especial + origen 'obra'
ALTER TABLE aridos_movimientos
  ADD COLUMN IF NOT EXISTS entrega_direccion TEXT,
  ADD COLUMN IF NOT EXISTS municipio_id INT REFERENCES aridos_municipios(id),
  ADD COLUMN IF NOT EXISTS precio_especial BOOLEAN NOT NULL DEFAULT false;

-- origen 'obra' = retiro de escombro: sale de la obra del cliente hacia
-- el depósito. No toca stock (el stock solo computa origen='deposito').
ALTER TABLE aridos_movimientos DROP CONSTRAINT IF EXISTS aridos_movimientos_origen_check;
ALTER TABLE aridos_movimientos
  ADD CONSTRAINT aridos_movimientos_origen_check CHECK (origen IN ('cantera', 'deposito', 'obra'));

-- Triggers touch + RLS permisiva para las tablas nuevas
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = '_alquiler_touch_updated_at') THEN
    CREATE TRIGGER trg_touch_aridos_municipios     BEFORE UPDATE ON aridos_municipios     FOR EACH ROW EXECUTE FUNCTION _alquiler_touch_updated_at();
    CREATE TRIGGER trg_touch_aridos_costos_cantera BEFORE UPDATE ON aridos_costos_cantera FOR EACH ROW EXECUTE FUNCTION _alquiler_touch_updated_at();
  END IF;
END $$;

ALTER TABLE aridos_municipios     ENABLE ROW LEVEL SECURITY;
ALTER TABLE aridos_costos_cantera ENABLE ROW LEVEL SECURITY;
CREATE POLICY aridos_municipios_all     ON aridos_municipios     FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY aridos_costos_cantera_all ON aridos_costos_cantera FOR ALL USING (true) WITH CHECK (true);
