-- 20260912g — Fotos en las fichas del catálogo de materiales (pedido del user 09/09):
-- "estaría bueno poder adjuntar fotos y que después se puedan consultar por si alguno tiene
-- una duda de si lo que quiere es eso".
--
-- Varias fotos por ficha (tabla), y una columna desnormalizada `stock_materiales.foto_url`
-- con la principal, mantenida por trigger, para que la lista de materiales que usa el
-- selector del pedido la traiga sin un join más. El bucket es PÚBLICO: son fotos de
-- productos, y las miniaturas se muestran de a cientos en el selector (firmar cada una
-- sería ridículo). Misma receta que herramienta_fotos (20260519), con `url` guardada.

create table if not exists public.stock_material_fotos (
  id            integer generated by default as identity primary key,
  material_id   integer not null references public.stock_materiales(id) on delete cascade,
  storage_path  text not null,
  url           text not null,
  file_hash     text,
  descripcion   text,
  orden         integer not null default 0,
  created_by    uuid,
  created_at    timestamptz not null default now(),
  deleted_at    timestamptz
);

comment on table public.stock_material_fotos is
  'Fotos de una ficha del catálogo (bucket público catalogo-fotos). La primera viva por orden es la principal (stock_materiales.foto_url).';

create index if not exists stock_material_fotos_mat_idx
  on public.stock_material_fotos (material_id, orden, id)
  where deleted_at is null;

-- La misma foto dos veces en la misma ficha no tiene sentido; en fichas distintas sí
-- (una foto de familia de productos).
create unique index if not exists stock_material_fotos_hash_uidx
  on public.stock_material_fotos (material_id, file_hash)
  where deleted_at is null and file_hash is not null;

alter table public.stock_material_fotos enable row level security;
drop policy if exists stock_material_fotos_all on public.stock_material_fotos;
create policy stock_material_fotos_all
  on public.stock_material_fotos for all
  using (true) with check (true);

alter table public.stock_materiales
  add column if not exists foto_url text;

comment on column public.stock_materiales.foto_url is
  'URL pública de la foto principal (la primera viva de stock_material_fotos). La mantiene el trigger; no escribirla a mano.';

create or replace function public.fn_stock_material_foto_url() returns trigger
language plpgsql as $$
declare
  v_material integer := coalesce(new.material_id, old.material_id);
begin
  update public.stock_materiales m
     set foto_url = (
       select f.url from public.stock_material_fotos f
        where f.material_id = v_material and f.deleted_at is null
        order by f.orden, f.id
        limit 1)
   where m.id = v_material;
  -- si cambió de ficha (no debería), la vieja también se recalcula
  if tg_op = 'UPDATE' and new.material_id <> old.material_id then
    update public.stock_materiales m
       set foto_url = (
         select f.url from public.stock_material_fotos f
          where f.material_id = old.material_id and f.deleted_at is null
          order by f.orden, f.id
          limit 1)
     where m.id = old.material_id;
  end if;
  return null;
end $$;

drop trigger if exists trg_stock_material_foto_url on public.stock_material_fotos;
create trigger trg_stock_material_foto_url
  after insert or update or delete on public.stock_material_fotos
  for each row execute function public.fn_stock_material_foto_url();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'catalogo-fotos',
  'catalogo-fotos',
  true,
  5242880,
  array['image/jpeg','image/png','image/webp','image/heic','image/heif']
)
on conflict (id) do nothing;

-- El catálogo la muestra: la columna va al final de la vista.
create or replace view public.v_catalogo_materiales with (security_invoker = on) as
 SELECT m.id,
    m.rubro_id,
    r.nombre AS rubro,
    r.icono AS rubro_icono,
    m.nombre,
    m.unidad,
    m.precio_ref,
    m.precio_actualizado_en,
    m.proveedor_id,
    pp.nombre AS proveedor_nombre,
    m.alias,
    m.clase,
    m.activo,
    m.usa_color,
    m.stock_actual,
    m.obs,
    m.updated_at,
    norm_txt((((m.nombre || ' '::text) || COALESCE(array_to_string(m.alias, ' '::text), ''::text)) || ' '::text) || r.nombre) AS busq,
    u.precio_unit AS uc_precio,
    u.proveedor_nombre AS uc_proveedor,
    u.fecha AS uc_fecha,
    u.solicitud_id AS uc_pedido,
    u.obra_cod AS uc_obra,
        CASE
            WHEN m.precio_ref = 0::numeric AND u.precio_unit IS NULL THEN 'sin_precio'::text
            WHEN m.precio_ref = 0::numeric THEN 'tasar'::text
            WHEN u.precio_unit IS NULL THEN 'sin_compra'::text
            WHEN NOT unidad_compatible(u.unidad, m.unidad) THEN 'unidad_distinta'::text
            WHEN (abs(u.precio_unit - m.precio_ref) / m.precio_ref) > 0.005 THEN 'desactualizado'::text
            ELSE 'al_dia'::text
        END AS estado_precio,
        CASE
            WHEN m.precio_ref > 0::numeric AND u.precio_unit IS NOT NULL AND unidad_compatible(u.unidad, m.unidad) THEN round((u.precio_unit - m.precio_ref) / m.precio_ref * 100::numeric)
            ELSE NULL::numeric
        END AS dif_pct,
    u.unidad AS uc_unidad,
    u.precio_unit IS NOT NULL AND unidad_compatible(u.unidad, m.unidad) AS uc_unidad_ok,
    m.foto_url
   FROM stock_materiales m
     JOIN stock_rubros r ON r.id = m.rubro_id
     LEFT JOIN proveedores pp ON pp.id = m.proveedor_id
     LEFT JOIN v_material_ultima_compra u ON u.material_id = m.id;
