-- ═══════════════════════════════════════════════════════════════════
--  ALQUILER — Fase C cuenta corriente: cobros del cliente
-- ───────────────────────────────────────────────────────────────────
--  Cobros (pagos) del cliente, a cuenta general (no imputados a una obra).
--  Saldo del cliente = devengado (Σ importes de partes) − Σ cobros.
--  Medio de pago: efectivo / transferencia / cheque / otro.
-- ═══════════════════════════════════════════════════════════════════

create table if not exists public.alquiler_cobros (
  id          integer generated by default as identity primary key,
  cliente_id  integer    not null references public.alquiler_clientes(id),  -- RESTRICT: no borrar cliente con cobros
  fecha       date       not null,
  monto       numeric    not null check (monto > 0),
  medio       text       not null default 'efectivo'
              check (medio in ('efectivo','transferencia','cheque','otro')),
  obs         text,
  created_by  uuid,
  created_at  timestamptz not null default now(),
  updated_by  uuid,
  updated_at  timestamptz not null default now()
);

create index if not exists alquiler_cobros_cliente_fecha_idx
  on public.alquiler_cobros (cliente_id, fecha);

create trigger trg_alquiler_cobros_touch
  before update on public.alquiler_cobros
  for each row execute function public._alquiler_touch_updated_at();

alter table public.alquiler_cobros enable row level security;
drop policy if exists alquiler_cobros_all on public.alquiler_cobros;
create policy alquiler_cobros_all on public.alquiler_cobros
  for all using (true) with check (true);
