-- =====================================================================
-- Seed complementario: más rubros y materiales de construcción
-- =====================================================================

-- ── Rubros nuevos ────────────────────────────────────────────────────
insert into stock_rubros (nombre, icono, orden) values
  ('Techado y cubiertas',    '🏠', 9),
  ('Aberturas',              '🚪', 10),
  ('Pisos y revestimientos', '🔲', 11),
  ('Instalación de gas',     '🔥', 12),
  ('Carpintería',            '🪵', 13),
  ('Hormigón y estructura',  '🏗️', 14),
  ('Seguridad y EPP',        '🦺', 15),
  ('Desagüe pluvial',        '🌧️', 16)
on conflict do nothing;

-- ═════════════════════════════════════════════════════════════════════
-- MÁS MATERIALES PARA RUBROS EXISTENTES
-- ═════════════════════════════════════════════════════════════════════

-- ── Sanitaria (complemento) ─────────────────────────────────────────
with r as (select id from stock_rubros where nombre = 'Sanitaria')
insert into stock_materiales (rubro_id, nombre, unidad) values
  ((select id from r), 'Caño PVC 32mm x 4m',           'unid'),
  ((select id from r), 'Caño PVC 160mm x 4m',          'unid'),
  ((select id from r), 'Codo PVC 63mm',                 'unid'),
  ((select id from r), 'Codo PVC 32mm',                 'unid'),
  ((select id from r), 'Te PVC 63mm',                   'unid'),
  ((select id from r), 'Te PVC 110 a 63mm',             'unid'),
  ((select id from r), 'Curva PVC 110mm larga',         'unid'),
  ((select id from r), 'Curva PVC 63mm larga',          'unid'),
  ((select id from r), 'Ramal PVC 110mm Y',             'unid'),
  ((select id from r), 'Ramal PVC 110 a 63mm Y',        'unid'),
  ((select id from r), 'Pileta de patio 15x15',         'unid'),
  ((select id from r), 'Cámara de inspección 20x20',    'unid'),
  ((select id from r), 'Cámara de inspección 30x30',    'unid'),
  ((select id from r), 'Cámara de inspección 40x40',    'unid'),
  ((select id from r), 'Reducción PVC 63 a 50mm',       'unid'),
  ((select id from r), 'Reducción PVC 50 a 40mm',       'unid'),
  ((select id from r), 'Reducción PVC 160 a 110mm',     'unid'),
  ((select id from r), 'Caño termofusión 32mm',         'm'),
  ((select id from r), 'Caño termofusión 40mm',         'm'),
  ((select id from r), 'Codo termofusión 32mm',         'unid'),
  ((select id from r), 'Te termofusión 25mm',           'unid'),
  ((select id from r), 'Te termofusión 32mm',           'unid'),
  ((select id from r), 'Cupla termofusión 25mm',        'unid'),
  ((select id from r), 'Cupla termofusión 32mm',        'unid'),
  ((select id from r), 'Rosca macho termofusión 1/2"',  'unid'),
  ((select id from r), 'Rosca macho termofusión 3/4"',  'unid'),
  ((select id from r), 'Rosca hembra termofusión 1/2"', 'unid'),
  ((select id from r), 'Rosca hembra termofusión 3/4"', 'unid'),
  ((select id from r), 'Llave de paso 1/2"',            'unid'),
  ((select id from r), 'Llave de paso 3/4"',            'unid'),
  ((select id from r), 'Llave de paso 1"',              'unid'),
  ((select id from r), 'Canilla de servicio 1/2"',      'unid'),
  ((select id from r), 'Grifería monocomando cocina',    'unid'),
  ((select id from r), 'Grifería monocomando baño',      'unid'),
  ((select id from r), 'Grifería ducha monocomando',     'unid'),
  ((select id from r), 'Duchador con flexible',          'unid'),
  ((select id from r), 'Termotanque eléctrico 50lts',   'unid'),
  ((select id from r), 'Termotanque eléctrico 80lts',   'unid'),
  ((select id from r), 'Termotanque a gas 50lts',       'unid'),
  ((select id from r), 'Calefón 14lts',                 'unid'),
  ((select id from r), 'Válvula retención 1/2"',        'unid'),
  ((select id from r), 'Válvula retención 3/4"',        'unid'),
  ((select id from r), 'Bomba presurizadora',            'unid'),
  ((select id from r), 'Rejilla de piso 10x10',         'unid'),
  ((select id from r), 'Rejilla de piso 20x20',         'unid'),
  ((select id from r), 'Sopapa p/ inodoro',              'unid'),
  ((select id from r), 'Aro de cera p/ inodoro',         'unid'),
  ((select id from r), 'Jabonera cerámica',              'unid'),
  ((select id from r), 'Toallero barra 60cm',           'unid'),
  ((select id from r), 'Portarrollo',                    'unid'),
  ((select id from r), 'Vanitory 60cm con mesada',       'unid'),
  ((select id from r), 'Espejo 60x80cm',                 'unid');

-- ── Electricidad (complemento) ──────────────────────────────────────
with r as (select id from stock_rubros where nombre = 'Electricidad')
insert into stock_materiales (rubro_id, nombre, unidad) values
  ((select id from r), 'Cable unipolar 16mm²',          'm'),
  ((select id from r), 'Cable unipolar 25mm²',          'm'),
  ((select id from r), 'Cable subterráneo 3x6mm²',      'm'),
  ((select id from r), 'Cable subterráneo 4x4mm²',      'm'),
  ((select id from r), 'Cable telefónico 2 pares',      'm'),
  ((select id from r), 'Cable UTP cat5e',                'm'),
  ((select id from r), 'Cable UTP cat6',                 'm'),
  ((select id from r), 'Cable coaxil RG6',               'm'),
  ((select id from r), 'Térmica 1x10A',                 'unid'),
  ((select id from r), 'Térmica 2x16A',                 'unid'),
  ((select id from r), 'Térmica 2x25A',                 'unid'),
  ((select id from r), 'Térmica 2x40A',                 'unid'),
  ((select id from r), 'Diferencial 4x25A 30mA',        'unid'),
  ((select id from r), 'Diferencial 4x40A 30mA',        'unid'),
  ((select id from r), 'Protector de tensión',           'unid'),
  ((select id from r), 'Contactor 25A',                  'unid'),
  ((select id from r), 'Timer analógico riel DIN',       'unid'),
  ((select id from r), 'Interruptor escalera',           'unid'),
  ((select id from r), 'Interruptor combinación',        'unid'),
  ((select id from r), 'Toma TV coaxil',                 'unid'),
  ((select id from r), 'Toma RJ45 datos',                'unid'),
  ((select id from r), 'Toma teléfono RJ11',             'unid'),
  ((select id from r), 'Tapa ciega',                     'unid'),
  ((select id from r), 'Caño rígido 3/4"',              'm'),
  ((select id from r), 'Caño rígido 1"',                'm'),
  ((select id from r), 'Curva rígida 3/4"',             'unid'),
  ((select id from r), 'Curva rígida 1"',               'unid'),
  ((select id from r), 'Conector caño rígido 3/4"',     'unid'),
  ((select id from r), 'Conector caño rígido 1"',       'unid'),
  ((select id from r), 'Bandeja portacable 100mm',       'm'),
  ((select id from r), 'Bandeja portacable 200mm',       'm'),
  ((select id from r), 'Borne p/ riel DIN 4mm²',        'unid'),
  ((select id from r), 'Borne p/ riel DIN 10mm²',       'unid'),
  ((select id from r), 'Timbre 220V',                    'unid'),
  ((select id from r), 'Pulsador de timbre',             'unid'),
  ((select id from r), 'Sensor de movimiento',           'unid'),
  ((select id from r), 'Lámpara LED 15W',                'unid'),
  ((select id from r), 'Lámpara LED 20W',                'unid'),
  ((select id from r), 'Proyector LED 30W',              'unid'),
  ((select id from r), 'Proyector LED 50W',              'unid'),
  ((select id from r), 'Proyector LED 100W',             'unid'),
  ((select id from r), 'Plafón LED 18W',                 'unid'),
  ((select id from r), 'Aplique pared exterior',         'unid'),
  ((select id from r), 'Grampa p/ cable 8mm',            'unid'),
  ((select id from r), 'Precintos plásticos 15cm',       'unid'),
  ((select id from r), 'Ficha macho 10A',                'unid'),
  ((select id from r), 'Ficha hembra 10A',               'unid'),
  ((select id from r), 'Prolongación 5m',                'unid'),
  ((select id from r), 'Prolongación 10m',               'unid'),
  ((select id from r), 'Prolongación 20m',               'unid');

-- ── Construcción en seco (complemento) ──────────────────────────────
with r as (select id from stock_rubros where nombre = 'Construcción en seco')
insert into stock_materiales (rubro_id, nombre, unidad) values
  ((select id from r), 'Placa Durlock STD 15mm',         'unid'),
  ((select id from r), 'Placa Superboard 6mm',           'unid'),
  ((select id from r), 'Placa Superboard 8mm',           'unid'),
  ((select id from r), 'Placa Superboard 10mm',          'unid'),
  ((select id from r), 'Montante 69mm x 3m',             'unid'),
  ((select id from r), 'Solera 69mm x 3m',               'unid'),
  ((select id from r), 'Montante 35mm x 3m',             'unid'),
  ((select id from r), 'Solera 35mm x 3m',               'unid'),
  ((select id from r), 'Perfil F 47mm',                   'unid'),
  ((select id from r), 'Clavo de impacto 27mm',           'unid'),
  ((select id from r), 'Clavo de impacto 37mm',           'unid'),
  ((select id from r), 'Esquinero plástico 2.60m',        'unid'),
  ((select id from r), 'Cinta guardacantos',               'rollo'),
  ((select id from r), 'Membrana Durlock acústica',        'rollo'),
  ((select id from r), 'Placa cementicia exterior 8mm',    'unid'),
  ((select id from r), 'Perfil U p/ cielorraso',           'unid'),
  ((select id from r), 'Varilla roscada 1/4"',             'unid'),
  ((select id from r), 'Hilo de colgar p/ cielorraso',     'm');

-- ── Albañilería (complemento) ───────────────────────────────────────
with r as (select id from stock_rubros where nombre = 'Albañilería')
insert into stock_materiales (rubro_id, nombre, unidad) values
  ((select id from r), 'Cemento de albañilería x 40kg',   'bolsa'),
  ((select id from r), 'Cal aérea x 25kg',                'bolsa'),
  ((select id from r), 'Cascote reciclado',                'tn'),
  ((select id from r), 'Tosca',                            'tn'),
  ((select id from r), 'Ladrillo visto',                   'unid'),
  ((select id from r), 'Ladrillo portante 12cm',           'unid'),
  ((select id from r), 'Ladrillo portante 18cm',           'unid'),
  ((select id from r), 'Bloque H 10cm',                    'unid'),
  ((select id from r), 'Bloque split 20cm',                'unid'),
  ((select id from r), 'Hierro Ø 4.2mm x 12m',            'unid'),
  ((select id from r), 'Hierro Ø 20mm x 12m',             'unid'),
  ((select id from r), 'Hierro Ø 25mm x 12m',             'unid'),
  ((select id from r), 'Estribo Ø 4.2mm 15x25',           'unid'),
  ((select id from r), 'Estribo Ø 4.2mm 20x30',           'unid'),
  ((select id from r), 'Estribo Ø 6mm 15x30',             'unid'),
  ((select id from r), 'Estribo Ø 6mm 20x40',             'unid'),
  ((select id from r), 'Alambre de atar N°18',             'kg'),
  ((select id from r), 'Separador plástico 2cm',           'unid'),
  ((select id from r), 'Separador plástico 3cm',           'unid'),
  ((select id from r), 'Separador plástico 5cm',           'unid'),
  ((select id from r), 'Piedra bola',                      'tn'),
  ((select id from r), 'Granza 6-19mm',                    'tn'),
  ((select id from r), 'Pegamento p/ porcelanato x 30kg',  'bolsa'),
  ((select id from r), 'Pegamento flex p/ piso s/ piso',   'bolsa'),
  ((select id from r), 'Pastina c/ arena x 5kg',           'unid'),
  ((select id from r), 'Hidrófugo x 5lts',                 'unid'),
  ((select id from r), 'Aditivo plastificante x 5lts',     'unid'),
  ((select id from r), 'Acelerante fraguado x 5lts',       'unid'),
  ((select id from r), 'Cinta de borde p/ carpeta',        'rollo'),
  ((select id from r), 'Malla electrosoldada 15x15 Ø 5mm', 'unid'),
  ((select id from r), 'Vigueta pretensada',                'unid'),
  ((select id from r), 'Ladrillo telgopor p/ losa',         'unid'),
  ((select id from r), 'Dintel premoldeado 1m',             'unid'),
  ((select id from r), 'Dintel premoldeado 1.5m',           'unid'),
  ((select id from r), 'Dintel premoldeado 2m',             'unid'),
  ((select id from r), 'Regla de aluminio 2m',              'unid'),
  ((select id from r), 'Regla de aluminio 3m',              'unid'),
  ((select id from r), 'Llana de acero',                    'unid'),
  ((select id from r), 'Fratacho espuma',                   'unid'),
  ((select id from r), 'Balde de albañil 12lts',            'unid');

-- ── Pintura (complemento) ───────────────────────────────────────────
with r as (select id from stock_rubros where nombre = 'Pintura')
insert into stock_materiales (rubro_id, nombre, unidad) values
  ((select id from r), 'Latex interior x 1lt',            'lata'),
  ((select id from r), 'Latex exterior x 1lt',            'lata'),
  ((select id from r), 'Enduido interior x 7kg',          'balde'),
  ((select id from r), 'Enduido exterior x 7kg',          'balde'),
  ((select id from r), 'Fijador sellador x 1lt',          'lata'),
  ((select id from r), 'Esmalte al agua x 4lts',          'lata'),
  ((select id from r), 'Esmalte al agua x 1lt',           'lata'),
  ((select id from r), 'Barniz marino x 4lts',            'lata'),
  ((select id from r), 'Barniz marino x 1lt',             'lata'),
  ((select id from r), 'Impermeabilizante acrílico x 20lts', 'lata'),
  ((select id from r), 'Impermeabilizante acrílico x 4lts',  'lata'),
  ((select id from r), 'Pintura p/ pileta x 4lts',        'lata'),
  ((select id from r), 'Pintura epoxi pisos x 4lts',      'lata'),
  ((select id from r), 'Pintura asfáltica x 18lts',       'lata'),
  ((select id from r), 'Pintura asfáltica x 4lts',        'lata'),
  ((select id from r), 'Aguarrás x 18lts',                'lata'),
  ((select id from r), 'Aguarrás x 4lts',                 'lata'),
  ((select id from r), 'Rodillo antigota 23cm',            'unid'),
  ((select id from r), 'Rodillo texturado 23cm',           'unid'),
  ((select id from r), 'Mini rodillo 10cm',                'unid'),
  ((select id from r), 'Pincel 1"',                        'unid'),
  ((select id from r), 'Pincel 4"',                        'unid'),
  ((select id from r), 'Bandeja p/ rodillo',               'unid'),
  ((select id from r), 'Espátula 80mm',                    'unid'),
  ((select id from r), 'Espátula 120mm',                   'unid'),
  ((select id from r), 'Cinta de pintor 24mm',             'rollo'),
  ((select id from r), 'Cinta de pintor 48mm',             'rollo'),
  ((select id from r), 'Film protector 3x4m',             'unid'),
  ((select id from r), 'Lija al agua N°60',               'unid'),
  ((select id from r), 'Lija al agua N°80',               'unid'),
  ((select id from r), 'Lija al agua N°320',              'unid'),
  ((select id from r), 'Lija al agua N°400',              'unid'),
  ((select id from r), 'Lija p/ madera N°80',             'unid'),
  ((select id from r), 'Lija p/ madera N°120',            'unid'),
  ((select id from r), 'Entonador universal',              'unid');

-- ── Ferretería general (complemento) ────────────────────────────────
with r as (select id from stock_rubros where nombre = 'Ferretería general')
insert into stock_materiales (rubro_id, nombre, unidad) values
  ((select id from r), 'Tornillo madera 3.5x25mm',        'unid'),
  ((select id from r), 'Tornillo madera 3.5x35mm',        'unid'),
  ((select id from r), 'Tornillo madera 5x50mm',          'unid'),
  ((select id from r), 'Tornillo madera 6x80mm',          'unid'),
  ((select id from r), 'Tornillo autoperf. punta mecha 10mm', 'unid'),
  ((select id from r), 'Tornillo autoperf. punta mecha 14mm', 'unid'),
  ((select id from r), 'Tarugo fisher 6mm c/tornillo',     'unid'),
  ((select id from r), 'Tarugo fisher 8mm c/tornillo',     'unid'),
  ((select id from r), 'Tarugo fisher 10mm c/tornillo',    'unid'),
  ((select id from r), 'Tarugo químico 12mm',              'unid'),
  ((select id from r), 'Clavos 1"',                        'kg'),
  ((select id from r), 'Clavos 1.5"',                      'kg'),
  ((select id from r), 'Clavos 4"',                        'kg'),
  ((select id from r), 'Bulón 6x50mm c/tuerca',           'unid'),
  ((select id from r), 'Bulón 8x60mm c/tuerca',           'unid'),
  ((select id from r), 'Bulón 12x120mm c/tuerca',         'unid'),
  ((select id from r), 'Bisagra pomela 3"',                'unid'),
  ((select id from r), 'Bisagra vaivén',                   'unid'),
  ((select id from r), 'Cierre automático',                'unid'),
  ((select id from r), 'Pasador hierro 6"',                'unid'),
  ((select id from r), 'Cadena galvanizada 3mm',           'm'),
  ((select id from r), 'Cadena galvanizada 5mm',           'm'),
  ((select id from r), 'Cerrojo de seguridad',             'unid'),
  ((select id from r), 'Manija puerta interior',           'unid'),
  ((select id from r), 'Manija puerta exterior',           'unid'),
  ((select id from r), 'Silicona acética transp. 280ml',   'unid'),
  ((select id from r), 'Silicona neutra transp. 280ml',    'unid'),
  ((select id from r), 'Adhesivo epoxi 2 componentes',     'unid'),
  ((select id from r), 'Cinta doble faz espuma',           'rollo'),
  ((select id from r), 'Cinta ducto gris 48mm',            'rollo'),
  ((select id from r), 'Precinto plástico 30cm',           'unid'),
  ((select id from r), 'Precinto plástico 40cm',           'unid'),
  ((select id from r), 'Linga con ganchos 2tn x 3m',      'unid'),
  ((select id from r), 'Soga polipropileno 8mm',           'm'),
  ((select id from r), 'Soga polipropileno 12mm',          'm'),
  ((select id from r), 'Alambre galvanizado N°14',         'kg');

-- ── Herrería (complemento) ──────────────────────────────────────────
with r as (select id from stock_rubros where nombre = 'Herrería')
insert into stock_materiales (rubro_id, nombre, unidad) values
  ((select id from r), 'Perfil C 160x60x20 x 6m',        'unid'),
  ((select id from r), 'Perfil C 200x50x15 x 6m',        'unid'),
  ((select id from r), 'IPN 80 x 6m',                      'unid'),
  ((select id from r), 'IPN 100 x 6m',                     'unid'),
  ((select id from r), 'IPN 120 x 6m',                     'unid'),
  ((select id from r), 'UPN 80 x 6m',                      'unid'),
  ((select id from r), 'UPN 100 x 6m',                     'unid'),
  ((select id from r), 'Ángulo 3/4" x 1/8" x 6m',        'unid'),
  ((select id from r), 'Ángulo 2-1/2" x 3/16" x 6m',     'unid'),
  ((select id from r), 'Caño estructural 80x40x2',         'unid'),
  ((select id from r), 'Caño estructural 100x50x2',        'unid'),
  ((select id from r), 'Caño estructural 40x20x1.6',       'unid'),
  ((select id from r), 'Caño redondo 3/4" x 6m',           'unid'),
  ((select id from r), 'Caño redondo 1-1/2" x 6m',         'unid'),
  ((select id from r), 'Caño redondo 2" x 6m',             'unid'),
  ((select id from r), 'Planchuela 2" x 3/16" x 6m',      'unid'),
  ((select id from r), 'Planchuela 3" x 1/4" x 6m',       'unid'),
  ((select id from r), 'Chapa lisa 1.25x2.50 N°18',        'unid'),
  ((select id from r), 'Chapa lisa 1.25x2.50 N°20',        'unid'),
  ((select id from r), 'Chapa perforada redonda',           'unid'),
  ((select id from r), 'Hierro plano 1/2" x 6m',           'unid'),
  ((select id from r), 'Hierro plano 3/4" x 6m',           'unid'),
  ((select id from r), 'Hierro redondo liso Ø 8mm x 6m',   'unid'),
  ((select id from r), 'Hierro redondo liso Ø 10mm x 6m',  'unid'),
  ((select id from r), 'Electrodo inoxidable 2.5mm',       'kg'),
  ((select id from r), 'Alambre MIG 0.8mm x 5kg',          'rollo'),
  ((select id from r), 'Gas CO2 x 10kg',                    'unid'),
  ((select id from r), 'Gas argón+CO2 x 10m³',             'unid'),
  ((select id from r), 'Disco corte 180mm',                 'unid'),
  ((select id from r), 'Disco diamantado 115mm',            'unid'),
  ((select id from r), 'Disco diamantado 230mm',            'unid'),
  ((select id from r), 'Mecha acero rápido 6mm',            'unid'),
  ((select id from r), 'Mecha acero rápido 8mm',            'unid'),
  ((select id from r), 'Mecha acero rápido 10mm',           'unid'),
  ((select id from r), 'Mecha acero rápido 12mm',           'unid'),
  ((select id from r), 'Mecha copa bimetálica 32mm',        'unid'),
  ((select id from r), 'Mecha copa bimetálica 51mm',        'unid'),
  ((select id from r), 'Convertidor de óxido x 4lts',       'lata'),
  ((select id from r), 'Antióxido x 1lt',                   'lata');

-- ── Aislación (complemento) ─────────────────────────────────────────
with r as (select id from stock_rubros where nombre = 'Aislación e impermeab.')
insert into stock_materiales (rubro_id, nombre, unidad) values
  ((select id from r), 'Membrana asfáltica 3mm x 10m²',     'rollo'),
  ((select id from r), 'Membrana asfáltica geotextil x 10m²', 'rollo'),
  ((select id from r), 'Membrana líquida x 5kg',             'balde'),
  ((select id from r), 'Primer asfáltico x 4lts',            'lata'),
  ((select id from r), 'Film polietileno 100 micrones',       'rollo'),
  ((select id from r), 'Film polietileno 200 micrones',       'rollo'),
  ((select id from r), 'Poliestireno expandido 30mm',         'm2'),
  ((select id from r), 'Poliestireno expandido 40mm',         'm2'),
  ((select id from r), 'Poliestireno extruido 30mm',          'm2'),
  ((select id from r), 'Poliestireno extruido 50mm',          'm2'),
  ((select id from r), 'Espuma de polietileno 5mm',           'm2'),
  ((select id from r), 'Espuma de polietileno 10mm',          'm2'),
  ((select id from r), 'Lana de vidrio rollo 50mm',           'rollo'),
  ((select id from r), 'Barrera de vapor aluminizada',         'rollo'),
  ((select id from r), 'Cinta asfáltica autoadhesiva 10cm',   'rollo'),
  ((select id from r), 'Cinta asfáltica autoadhesiva 15cm',   'rollo');

-- ═════════════════════════════════════════════════════════════════════
-- RUBROS NUEVOS
-- ═════════════════════════════════════════════════════════════════════

-- ── Techado y cubiertas ─────────────────────────────────────────────
with r as (select id from stock_rubros where nombre = 'Techado y cubiertas')
insert into stock_materiales (rubro_id, nombre, unidad) values
  ((select id from r), 'Chapa sinusoidal galv. C25 1.10x3m', 'unid'),
  ((select id from r), 'Chapa sinusoidal galv. C25 1.10x4m', 'unid'),
  ((select id from r), 'Chapa sinusoidal galv. C25 1.10x5m', 'unid'),
  ((select id from r), 'Chapa sinusoidal galv. C25 1.10x6m', 'unid'),
  ((select id from r), 'Chapa trapezoidal galv. C25 1.10x3m', 'unid'),
  ((select id from r), 'Chapa trapezoidal galv. C25 1.10x4m', 'unid'),
  ((select id from r), 'Chapa trapezoidal galv. C25 1.10x5m', 'unid'),
  ((select id from r), 'Chapa trapezoidal galv. C25 1.10x6m', 'unid'),
  ((select id from r), 'Chapa trapezoidal color C25 1.10x4m', 'unid'),
  ((select id from r), 'Chapa trapezoidal color C25 1.10x6m', 'unid'),
  ((select id from r), 'Chapa canaleta galv. 1.10x3m',        'unid'),
  ((select id from r), 'Chapa canaleta galv. 1.10x4m',        'unid'),
  ((select id from r), 'Tornillo autoperf. p/ chapa 14x1"',   'unid'),
  ((select id from r), 'Tornillo autoperf. p/ chapa 14x2"',   'unid'),
  ((select id from r), 'Tornillo autoperf. p/ chapa 14x3"',   'unid'),
  ((select id from r), 'Arandela c/ neoprene p/ chapa',        'unid'),
  ((select id from r), 'Cumbrera galvanizada',                  'unid'),
  ((select id from r), 'Cumbrera color',                        'unid'),
  ((select id from r), 'Cenefa galvanizada',                    'unid'),
  ((select id from r), 'Remate lateral galvanizado',            'unid'),
  ((select id from r), 'Canaleta lluvia galv. 100mm x 3m',     'unid'),
  ((select id from r), 'Canaleta lluvia galv. 150mm x 3m',     'unid'),
  ((select id from r), 'Bajada pluvial galv. 100mm x 3m',      'unid'),
  ((select id from r), 'Bajada pluvial PVC 110mm x 3m',        'unid'),
  ((select id from r), 'Soporte p/ canaleta',                   'unid'),
  ((select id from r), 'Codo bajada 90° 110mm',                 'unid'),
  ((select id from r), 'Chapa policarbonato alveolar 6mm x 3m', 'unid'),
  ((select id from r), 'Chapa policarbonato alveolar 6mm x 4m', 'unid'),
  ((select id from r), 'Chapa fibrocemento ondulada 1.10x3m',   'unid'),
  ((select id from r), 'Teja colonial cerámica',                 'unid'),
  ((select id from r), 'Tirante pino 2x4" x 4m',                'unid'),
  ((select id from r), 'Tirante pino 2x6" x 4m',                'unid'),
  ((select id from r), 'Tirante pino 3x6" x 4m',                'unid'),
  ((select id from r), 'Machimbre pino 1/2" x 4" x 3.35m',     'unid'),
  ((select id from r), 'Machimbre pino 1/2" x 5" x 3.35m',     'unid'),
  ((select id from r), 'Clavo espiralado p/ chapa 2"',          'kg');

-- ── Aberturas ───────────────────────────────────────────────────────
with r as (select id from stock_rubros where nombre = 'Aberturas')
insert into stock_materiales (rubro_id, nombre, unidad) values
  ((select id from r), 'Puerta placa interior 70cm',        'unid'),
  ((select id from r), 'Puerta placa interior 80cm',        'unid'),
  ((select id from r), 'Puerta placa interior 90cm',        'unid'),
  ((select id from r), 'Puerta exterior chapa reforzada',    'unid'),
  ((select id from r), 'Puerta cortafuego 80cm',            'unid'),
  ((select id from r), 'Marco puerta madera 70cm',          'unid'),
  ((select id from r), 'Marco puerta madera 80cm',          'unid'),
  ((select id from r), 'Marco puerta madera 90cm',          'unid'),
  ((select id from r), 'Marco puerta metálico 80cm',        'unid'),
  ((select id from r), 'Marco puerta metálico 90cm',        'unid'),
  ((select id from r), 'Ventana aluminio corrediza 1.50x1.10', 'unid'),
  ((select id from r), 'Ventana aluminio corrediza 1.20x1.10', 'unid'),
  ((select id from r), 'Ventana aluminio corrediza 1.00x1.00', 'unid'),
  ((select id from r), 'Ventana aluminio corrediza 2.00x1.50', 'unid'),
  ((select id from r), 'Ventana aluminio banderola 60x40',     'unid'),
  ((select id from r), 'Ventana aluminio banderola 80x40',     'unid'),
  ((select id from r), 'Ventana aluminio de abrir 60x110',     'unid'),
  ((select id from r), 'Puerta ventana aluminio 1.50x2.00',    'unid'),
  ((select id from r), 'Puerta ventana aluminio 2.00x2.00',    'unid'),
  ((select id from r), 'Vidrio float 4mm',                  'm2'),
  ((select id from r), 'Vidrio float 6mm',                  'm2'),
  ((select id from r), 'DVH 4+9+4mm',                       'm2'),
  ((select id from r), 'Mampara ducha fija 80cm',            'unid'),
  ((select id from r), 'Reja p/ ventana a medida',            'm2'),
  ((select id from r), 'Mosquitero aluminio corredizo',       'unid'),
  ((select id from r), 'Umbral aluminio 80cm',                'unid'),
  ((select id from r), 'Tapajuntas aluminio 3m',              'unid'),
  ((select id from r), 'Burlete autoadhesivo espuma',          'm');

-- ── Pisos y revestimientos ──────────────────────────────────────────
with r as (select id from stock_rubros where nombre = 'Pisos y revestimientos')
insert into stock_materiales (rubro_id, nombre, unidad) values
  ((select id from r), 'Cerámico piso 30x30',              'm2'),
  ((select id from r), 'Cerámico piso 40x40',              'm2'),
  ((select id from r), 'Cerámico piso 45x45',              'm2'),
  ((select id from r), 'Cerámico pared 20x30',             'm2'),
  ((select id from r), 'Cerámico pared 25x35',             'm2'),
  ((select id from r), 'Cerámico pared 30x45',             'm2'),
  ((select id from r), 'Porcelanato pulido 60x60',          'm2'),
  ((select id from r), 'Porcelanato mate 60x60',            'm2'),
  ((select id from r), 'Porcelanato simil madera 20x120',   'm2'),
  ((select id from r), 'Porcelanato simil cemento 60x60',   'm2'),
  ((select id from r), 'Porcelanato exterior antidesl.',     'm2'),
  ((select id from r), 'Piso calcáreo 20x20',               'm2'),
  ((select id from r), 'Piso calcáreo 30x30',               'm2'),
  ((select id from r), 'Baldosón veredón 40x40',            'unid'),
  ((select id from r), 'Mosaico granítico 30x30',           'm2'),
  ((select id from r), 'Piso vinílico SPC click',           'm2'),
  ((select id from r), 'Piso flotante laminado 8mm',        'm2'),
  ((select id from r), 'Zócalo cerámico 7x30',              'm'),
  ((select id from r), 'Zócalo porcelanato 7x60',           'm'),
  ((select id from r), 'Zócalo MDF 7cm',                    'm'),
  ((select id from r), 'Guardas decorativas',                'm'),
  ((select id from r), 'Perfil transición aluminio',         'm'),
  ((select id from r), 'Crucetas separadoras 2mm',           'unid'),
  ((select id from r), 'Crucetas separadoras 3mm',           'unid'),
  ((select id from r), 'Niveladores piso (cuña + base)',     'unid'),
  ((select id from r), 'Alfajía pino 1x2" x 3.35m',         'unid'),
  ((select id from r), 'Deck WPC tabla 14.5x2.3cm x 2.20m', 'unid'),
  ((select id from r), 'Canto rodado bolsa 25kg',             'bolsa');

-- ── Instalación de gas ──────────────────────────────────────────────
with r as (select id from stock_rubros where nombre = 'Instalación de gas')
insert into stock_materiales (rubro_id, nombre, unidad) values
  ((select id from r), 'Caño epoxi gas 1/2" x 6m',         'unid'),
  ((select id from r), 'Caño epoxi gas 3/4" x 6m',         'unid'),
  ((select id from r), 'Caño epoxi gas 1" x 6m',           'unid'),
  ((select id from r), 'Caño hierro negro 1/2" x 6m',       'unid'),
  ((select id from r), 'Caño hierro negro 3/4" x 6m',       'unid'),
  ((select id from r), 'Caño hierro negro 1" x 6m',         'unid'),
  ((select id from r), 'Codo epoxi gas 1/2"',               'unid'),
  ((select id from r), 'Codo epoxi gas 3/4"',               'unid'),
  ((select id from r), 'Te epoxi gas 1/2"',                 'unid'),
  ((select id from r), 'Te epoxi gas 3/4"',                 'unid'),
  ((select id from r), 'Cupla epoxi gas 1/2"',              'unid'),
  ((select id from r), 'Niple epoxi gas 1/2"',              'unid'),
  ((select id from r), 'Llave de paso gas 1/2"',             'unid'),
  ((select id from r), 'Llave de paso gas 3/4"',             'unid'),
  ((select id from r), 'Regulador gas baja presión',          'unid'),
  ((select id from r), 'Regulador gas alta presión',          'unid'),
  ((select id from r), 'Flexible gas 1/2" x 50cm',           'unid'),
  ((select id from r), 'Flexible gas 1/2" x 100cm',          'unid'),
  ((select id from r), 'Cinta teflón gas (amarilla)',         'unid'),
  ((select id from r), 'Sellador anaeróbico gas',             'unid'),
  ((select id from r), 'Medidor gas domiciliario',            'unid'),
  ((select id from r), 'Gabinete p/ medidor gas',             'unid'),
  ((select id from r), 'Cocina 4 hornallas + horno',          'unid'),
  ((select id from r), 'Anafe 4 hornallas',                   'unid'),
  ((select id from r), 'Calefactor tiro balanceado 3000kcal',  'unid'),
  ((select id from r), 'Calefactor tiro balanceado 5000kcal',  'unid'),
  ((select id from r), 'Estufa infrarroja 2 velas',            'unid'),
  ((select id from r), 'Ventilación gas 15x15',                'unid'),
  ((select id from r), 'Ventilación gas 20x20',                'unid'),
  ((select id from r), 'Sombrerete ventilación gas',            'unid');

-- ── Carpintería ─────────────────────────────────────────────────────
with r as (select id from stock_rubros where nombre = 'Carpintería')
insert into stock_materiales (rubro_id, nombre, unidad) values
  ((select id from r), 'Fenólico 18mm 1.22x2.44',          'unid'),
  ((select id from r), 'Fenólico 15mm 1.22x2.44',          'unid'),
  ((select id from r), 'Fenólico 12mm 1.22x2.44',          'unid'),
  ((select id from r), 'Fenólico plastificado 18mm',        'unid'),
  ((select id from r), 'OSB 11mm 1.22x2.44',               'unid'),
  ((select id from r), 'OSB 15mm 1.22x2.44',               'unid'),
  ((select id from r), 'MDF 3mm 1.83x2.60',                 'unid'),
  ((select id from r), 'MDF 5.5mm 1.83x2.60',               'unid'),
  ((select id from r), 'MDF 18mm 1.83x2.60',                'unid'),
  ((select id from r), 'Melamina blanca 18mm 1.83x2.60',    'unid'),
  ((select id from r), 'Melamina roble 18mm 1.83x2.60',     'unid'),
  ((select id from r), 'Melamina gris 18mm 1.83x2.60',      'unid'),
  ((select id from r), 'Aglomerado 18mm 1.83x2.60',         'unid'),
  ((select id from r), 'Tabla pino cepillada 1x4" x 3.35m', 'unid'),
  ((select id from r), 'Tabla pino cepillada 1x6" x 3.35m', 'unid'),
  ((select id from r), 'Tabla pino cepillada 1x8" x 3.35m', 'unid'),
  ((select id from r), 'Listón pino 1x1" x 3.35m',          'unid'),
  ((select id from r), 'Listón pino 1x2" x 3.35m',          'unid'),
  ((select id from r), 'Listón pino 2x2" x 3.35m',          'unid'),
  ((select id from r), 'Tirante pino 2x3" x 4m',            'unid'),
  ((select id from r), 'Tirante pino 3x3" x 4m',            'unid'),
  ((select id from r), 'Varilla pino redonda 25mm x 1m',     'unid'),
  ((select id from r), 'Cola vinílica x 5kg',                 'unid'),
  ((select id from r), 'Cola vinílica x 1kg',                 'unid'),
  ((select id from r), 'Tapatornillo adhesivo blanco',         'unid'),
  ((select id from r), 'Tapatornillo adhesivo roble',          'unid'),
  ((select id from r), 'Cantonera PVC 2.60m',                 'unid'),
  ((select id from r), 'Tapacanto melamina blanco rollo',      'rollo'),
  ((select id from r), 'Tapacanto melamina roble rollo',       'rollo');

-- ── Hormigón y estructura ───────────────────────────────────────────
with r as (select id from stock_rubros where nombre = 'Hormigón y estructura')
insert into stock_materiales (rubro_id, nombre, unidad) values
  ((select id from r), 'Hormigón elaborado H21',            'm3'),
  ((select id from r), 'Hormigón elaborado H25',            'm3'),
  ((select id from r), 'Hormigón elaborado H30',            'm3'),
  ((select id from r), 'Cemento ARS x 50kg',                'bolsa'),
  ((select id from r), 'Aditivo plastificante x 20lts',     'balde'),
  ((select id from r), 'Aditivo acelerante x 20lts',        'balde'),
  ((select id from r), 'Aditivo retardante x 20lts',        'balde'),
  ((select id from r), 'Fibra polipropileno x 600g',        'unid'),
  ((select id from r), 'Desmoldante p/ encofrado x 20lts',  'balde'),
  ((select id from r), 'Curador de hormigón x 20lts',       'balde'),
  ((select id from r), 'Grout cementicio x 25kg',           'bolsa'),
  ((select id from r), 'Mortero autonivelante x 25kg',       'bolsa'),
  ((select id from r), 'Anclaje químico cartucho',            'unid'),
  ((select id from r), 'Barra roscada Ø 12mm x 1m',          'unid'),
  ((select id from r), 'Barra roscada Ø 16mm x 1m',          'unid'),
  ((select id from r), 'Placa base 200x200x8mm',              'unid'),
  ((select id from r), 'Placa base 250x250x10mm',             'unid'),
  ((select id from r), 'Encofrado fenólico p/ columna',        'unid'),
  ((select id from r), 'Puntal metálico regulable 3m',         'unid'),
  ((select id from r), 'Puntal metálico regulable 4m',         'unid'),
  ((select id from r), 'Tablón pino encofrado 1" x 4m',        'unid'),
  ((select id from r), 'Alambre recocido N°16',                 'kg'),
  ((select id from r), 'Separador silla 3cm',                   'unid'),
  ((select id from r), 'Separador silla 5cm',                   'unid'),
  ((select id from r), 'Junta de dilatación PVC 15cm',          'm');

-- ── Seguridad y EPP ─────────────────────────────────────────────────
with r as (select id from stock_rubros where nombre = 'Seguridad y EPP')
insert into stock_materiales (rubro_id, nombre, unidad) values
  ((select id from r), 'Casco seguridad c/ arnés',           'unid'),
  ((select id from r), 'Lentes seguridad transparentes',      'unid'),
  ((select id from r), 'Lentes seguridad oscuros',            'unid'),
  ((select id from r), 'Protector auditivo endoaural',         'unid'),
  ((select id from r), 'Protector auditivo copa',              'unid'),
  ((select id from r), 'Guante descarne corto',                'unid'),
  ((select id from r), 'Guante descarne largo (soldador)',     'unid'),
  ((select id from r), 'Guante nitrilo descartable',           'unid'),
  ((select id from r), 'Guante anticorte',                     'unid'),
  ((select id from r), 'Guante latex multiuso',                'unid'),
  ((select id from r), 'Barbijo descartable',                  'unid'),
  ((select id from r), 'Semimáscara c/ filtro polvo',           'unid'),
  ((select id from r), 'Máscara soldar fotosensible',           'unid'),
  ((select id from r), 'Arnés seguridad 3 puntos',              'unid'),
  ((select id from r), 'Cabo vida 1.5m c/ mosquetón',           'unid'),
  ((select id from r), 'Chaleco reflectivo',                     'unid'),
  ((select id from r), 'Botín seguridad punta acero',            'unid'),
  ((select id from r), 'Bota de lluvia PVC caña alta',           'unid'),
  ((select id from r), 'Mameluco descartable',                    'unid'),
  ((select id from r), 'Delantal de cuero soldador',              'unid'),
  ((select id from r), 'Polainas de cuero soldador',              'unid'),
  ((select id from r), 'Cinta peligro roja/blanca 200m',          'rollo'),
  ((select id from r), 'Cinta peligro amarilla/negra 200m',       'rollo'),
  ((select id from r), 'Cartel "Obra en construcción"',            'unid'),
  ((select id from r), 'Cartel "Uso obligatorio EPP"',             'unid'),
  ((select id from r), 'Cartel "Peligro eléctrico"',               'unid'),
  ((select id from r), 'Matafuego ABC 5kg',                        'unid'),
  ((select id from r), 'Matafuego ABC 10kg',                       'unid'),
  ((select id from r), 'Botiquín primeros auxilios',                'unid'),
  ((select id from r), 'Baranda provisoria p/ losa (por tramo)',    'unid');

-- ── Desagüe pluvial ─────────────────────────────────────────────────
with r as (select id from stock_rubros where nombre = 'Desagüe pluvial')
insert into stock_materiales (rubro_id, nombre, unidad) values
  ((select id from r), 'Caño PVC pluvial 110mm x 4m',        'unid'),
  ((select id from r), 'Caño PVC pluvial 63mm x 4m',         'unid'),
  ((select id from r), 'Codo PVC pluvial 110mm 90°',         'unid'),
  ((select id from r), 'Codo PVC pluvial 110mm 45°',         'unid'),
  ((select id from r), 'Codo PVC pluvial 63mm 90°',          'unid'),
  ((select id from r), 'Te PVC pluvial 110mm',                'unid'),
  ((select id from r), 'Reducción PVC pluvial 110 a 63mm',    'unid'),
  ((select id from r), 'Embudo pluvial 110mm',                 'unid'),
  ((select id from r), 'Embudo pluvial con reja 110mm',        'unid'),
  ((select id from r), 'Soporte caño pluvial 110mm',           'unid'),
  ((select id from r), 'Soporte caño pluvial 63mm',            'unid'),
  ((select id from r), 'Caño corrugado drenaje 110mm',          'm'),
  ((select id from r), 'Caño corrugado drenaje 160mm',          'm'),
  ((select id from r), 'Geotextil no tejido 200g/m²',           'm2'),
  ((select id from r), 'Cámara pluvial 30x30',                  'unid'),
  ((select id from r), 'Cámara pluvial 40x40',                  'unid'),
  ((select id from r), 'Reja desagüe lineal 1m',                'unid'),
  ((select id from r), 'Canaleta desagüe lineal c/ reja 1m',    'unid');
