-- Lugares operativos (puntos físicos: mantenimiento, relevos/intercambios,
-- estacionamiento — p.ej. CHIVILCOY). En el modelo de tramos un endpoint es
-- cantera (origen) o depósito (destino), así que un lugar operativo se
-- representa como un PAR cantera+depósito (ambos operativo=true). Esta tabla
-- los UNIFICA: una fila = un lugar operativo, que apunta a su cantera y su
-- depósito. El usuario lo gestiona como un solo concepto y el modelo de tramos
-- queda intacto (sigue usando cantera_id/deposito_id).
create table public.lugares_operativos (
  id          integer generated by default as identity primary key,
  nombre      text    not null,
  cantera_id  integer not null references public.canteras(id),
  deposito_id integer not null references public.depositos(id),
  obs         text,
  created_by  uuid,
  created_at  timestamptz not null default now(),
  updated_by  uuid,
  updated_at  timestamptz not null default now()
);
-- Cada cantera/depósito pertenece a lo sumo a un lugar operativo.
create unique index lugares_operativos_cantera_uq  on public.lugares_operativos(cantera_id);
create unique index lugares_operativos_deposito_uq on public.lugares_operativos(deposito_id);

alter table public.lugares_operativos enable row level security;
drop policy if exists lugares_operativos_all on public.lugares_operativos;
create policy lugares_operativos_all on public.lugares_operativos
  for all using (true) with check (true);

-- Traer el CHIVILCOY existente a este modelo (cantera "CHIVILCOY CANT" + depósito
-- "CHIVILCOY", ambos ya marcados operativo). Idempotente.
insert into public.lugares_operativos (nombre, cantera_id, deposito_id)
select 'CHIVILCOY',
       (select id from public.canteras  where nombre ilike '%chivilcoy%' and operativo order by id limit 1),
       (select id from public.depositos where nombre ilike '%chivilcoy%' and operativo order by id limit 1)
where exists (select 1 from public.canteras  where nombre ilike '%chivilcoy%' and operativo)
  and exists (select 1 from public.depositos where nombre ilike '%chivilcoy%' and operativo)
  and not exists (select 1 from public.lugares_operativos);
