-- Flota CADINC — Fase 3: columnas GPS para sync con MobilQuest.
-- mobilquest_device_id e mobilquest_ultima_sync_at ya existen (creadas en
-- Fase 1). Acá agregamos los campos que vienen de cada lectura GPS, más
-- el estado/error del último intento de sync. Naming alineado al patrón
-- gps_* de la tabla camiones para que ambos módulos compartan vocabulario.

alter table public.flota_vehiculos
  add column if not exists gps_ultima_lat             numeric,
  add column if not exists gps_ultima_lng             numeric,
  add column if not exists gps_ultima_velocidad       numeric,
  add column if not exists gps_ultima_lectura_en      timestamptz,
  add column if not exists gps_ultimo_sync_estado     text,
  add column if not exists gps_ultimo_sync_error      text,
  add column if not exists km_actualizado_en          timestamptz;

create index if not exists flota_vehiculos_mq_device_idx
  on public.flota_vehiculos (mobilquest_device_id)
  where mobilquest_device_id is not null;

-- Tabla de bitácora de syncs (espejo del patrón gps_sync_log de camiones).
create table if not exists public.flota_gps_sync_log (
  id              integer generated by default as identity primary key,
  vehiculo_id     integer references public.flota_vehiculos(id) on delete set null,
  id_vehiculo_gps text,
  patente_gps     text,
  tipo            text not null check (tipo in ('manual_individual','manual_global','cron')),
  estado          text not null check (estado in ('ok','sin_cambio','error','no_match')),
  km_anterior     numeric,
  km_nuevo        numeric,
  velocidad       numeric,
  lectura_gps_en  timestamptz,
  error_mensaje   text,
  duracion_ms     integer,
  created_at      timestamptz not null default now(),
  created_by      uuid
);

create index if not exists flota_gps_sync_log_vehiculo_idx
  on public.flota_gps_sync_log (vehiculo_id, created_at desc);

alter table public.flota_gps_sync_log enable row level security;
drop policy if exists flota_gps_sync_log_all on public.flota_gps_sync_log;
create policy flota_gps_sync_log_all
  on public.flota_gps_sync_log for all
  using (true) with check (true);
