-- Fotos de herramientas — galería de imágenes por cada herramienta del
-- inventario. Útil para registrar estado, accesorios, número de serie en
-- la chapita, etc.

create table if not exists public.herramienta_fotos (
  id              integer generated by default as identity primary key,
  herramienta_id  integer not null references public.herramientas(id) on delete cascade,
  storage_path    text not null,
  file_hash       text unique,
  descripcion     text,
  orden           integer not null default 0,
  created_by      uuid,
  created_at      timestamptz not null default now(),
  deleted_at      timestamptz
);

create index if not exists herramienta_fotos_herr_idx
  on public.herramienta_fotos (herramienta_id, orden)
  where deleted_at is null;

alter table public.herramienta_fotos enable row level security;
drop policy if exists herramienta_fotos_all on public.herramienta_fotos;
create policy herramienta_fotos_all
  on public.herramienta_fotos for all
  using (true) with check (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'herramienta-fotos',
  'herramienta-fotos',
  false,
  5242880,
  array['image/jpeg','image/png','image/webp','image/heic','image/heif']
)
on conflict (id) do nothing;
