-- ════════════════════════════════════════════════════════════════════
-- Áridos v1.3 — cuenta corriente con CANTERAS (proveedores).
-- Las canteras no son propias: se les retira material y se les debe.
-- La lista de precios real de una cantera (ej. Áridos Centeno) es por
-- VIAJE, con conceptos propios ("Viaje de Arena fina", "Viaje Mixto…")
-- y precios por ZONA de entrega — no mapea 1:1 al catálogo de
-- materiales. Por eso:
--   1. aridos_costos_cantera pasa a concepto (texto) × zona (texto),
--      con material_id opcional como link informativo.
--   2. El movimiento guarda costo_unit/costo_total (lo que cobró la
--      cantera por ESE retiro) — snapshot exacto para la cta cte.
--   3. aridos_pagos_cantera registra los pagos al proveedor.
--      Saldo cantera = Σ costo_total de sus movimientos − Σ pagos.
-- ════════════════════════════════════════════════════════════════════

-- Lista de precios de la cantera: concepto × zona, historial por vigencia
ALTER TABLE aridos_costos_cantera
  ADD COLUMN IF NOT EXISTS concepto TEXT,
  ADD COLUMN IF NOT EXISTS zona     TEXT,
  ALTER COLUMN material_id DROP NOT NULL;

-- Lo que cobró la cantera por el retiro (snapshot, editable al cargar)
ALTER TABLE aridos_movimientos
  ADD COLUMN IF NOT EXISTS costo_unit  NUMERIC,
  ADD COLUMN IF NOT EXISTS costo_total NUMERIC;

-- Pagos al proveedor (cta cte: saldo = retirado − pagado)
CREATE TABLE IF NOT EXISTS aridos_pagos_cantera (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cantera_id INT NOT NULL REFERENCES aridos_canteras(id) ON DELETE RESTRICT,
  fecha      DATE NOT NULL DEFAULT CURRENT_DATE,
  monto      NUMERIC NOT NULL CHECK (monto > 0),
  medio      TEXT NOT NULL DEFAULT 'transferencia' CHECK (medio IN ('efectivo', 'transferencia', 'cheque', 'otro')),
  obs        TEXT,
  created_by UUID,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_by UUID,
  updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_aridos_pagos_cantera ON aridos_pagos_cantera (cantera_id, fecha);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = '_alquiler_touch_updated_at') THEN
    CREATE TRIGGER trg_touch_aridos_pagos_cantera BEFORE UPDATE ON aridos_pagos_cantera FOR EACH ROW EXECUTE FUNCTION _alquiler_touch_updated_at();
  END IF;
END $$;

ALTER TABLE aridos_pagos_cantera ENABLE ROW LEVEL SECURITY;
CREATE POLICY aridos_pagos_cantera_all ON aridos_pagos_cantera FOR ALL USING (true) WITH CHECK (true);
