-- ════════════════════════════════════════════════════════════════════
-- Áridos v1.2 — canteras y unidades PROPIAS del negocio de áridos.
-- Áridos es otro brazo de la empresa: sus canteras, camiones y choferes
-- NO son los de logística. Se reemplazan las FKs a canteras/choferes/
-- camiones de logística por tablas propias:
--   - aridos_canteras: canteras del negocio de áridos (con ubicación).
--   - aridos_unidades: equipo camión+chofer, con GPS Mobile Quest
--     (mismo patrón de mapping por patente que camiones de logística)
--     para calcular tiempo de llegada a destino vía Google Maps.
-- Las columnas viejas estaban vacías en prod (verificado 2026-06-12).
-- ════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS aridos_canteras (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre     TEXT NOT NULL UNIQUE,
  direccion  TEXT,
  localidad  TEXT,
  lat        NUMERIC(10,7),
  lng        NUMERIC(10,7),
  obs        TEXT,
  activo     BOOLEAN NOT NULL DEFAULT true,
  created_by UUID,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_by UUID,
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS aridos_unidades (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre     TEXT NOT NULL,
  patente    TEXT NOT NULL UNIQUE,
  chofer     TEXT,
  activo     BOOLEAN NOT NULL DEFAULT true,
  -- GPS Mobile Quest (mismo esquema que camiones de logística):
  -- el mapping id_vehiculo_gps se resuelve automático por patente.
  id_vehiculo_gps       TEXT,
  gps_ultima_lat        NUMERIC(10,7),
  gps_ultima_lng        NUMERIC(10,7),
  gps_ultima_velocidad  NUMERIC(6,2),
  gps_ultima_lectura_en TIMESTAMPTZ,
  obs        TEXT,
  created_by UUID,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_by UUID,
  updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS aridos_unidades_id_vehiculo_gps_uq
  ON aridos_unidades (id_vehiculo_gps) WHERE id_vehiculo_gps IS NOT NULL;

-- Movimientos: chofer/camión de logística → unidad propia; cantera de
-- logística → cantera propia. Columnas viejas vacías, drop directo.
ALTER TABLE aridos_movimientos
  DROP COLUMN IF EXISTS chofer_id,
  DROP COLUMN IF EXISTS camion_id;
ALTER TABLE aridos_movimientos
  ADD COLUMN IF NOT EXISTS unidad_id INT REFERENCES aridos_unidades(id);

ALTER TABLE aridos_movimientos DROP CONSTRAINT IF EXISTS aridos_movimientos_cantera_id_fkey;
ALTER TABLE aridos_movimientos
  ADD CONSTRAINT aridos_movimientos_cantera_id_fkey
  FOREIGN KEY (cantera_id) REFERENCES aridos_canteras(id);

-- Costos de compra: repuntar a canteras propias (tabla vacía en prod).
ALTER TABLE aridos_costos_cantera DROP CONSTRAINT IF EXISTS aridos_costos_cantera_cantera_id_fkey;
ALTER TABLE aridos_costos_cantera
  ADD CONSTRAINT aridos_costos_cantera_cantera_id_fkey
  FOREIGN KEY (cantera_id) REFERENCES aridos_canteras(id) ON DELETE CASCADE;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = '_alquiler_touch_updated_at') THEN
    CREATE TRIGGER trg_touch_aridos_canteras BEFORE UPDATE ON aridos_canteras FOR EACH ROW EXECUTE FUNCTION _alquiler_touch_updated_at();
    CREATE TRIGGER trg_touch_aridos_unidades BEFORE UPDATE ON aridos_unidades FOR EACH ROW EXECUTE FUNCTION _alquiler_touch_updated_at();
  END IF;
END $$;

ALTER TABLE aridos_canteras ENABLE ROW LEVEL SECURITY;
ALTER TABLE aridos_unidades ENABLE ROW LEVEL SECURITY;
CREATE POLICY aridos_canteras_all ON aridos_canteras FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY aridos_unidades_all ON aridos_unidades FOR ALL USING (true) WITH CHECK (true);
